### ISSUE TITLE
Orphaned Channels

### ISSUE THREAD

**Issue by cicoyle** [dapr/java-sdk#1002]
## Expected Behavior

I would expect to be able to run `./mvnw -B test -q ` in CI & locally without seeing a bunch of managed orphan channels not being shutdown properly. I would have thought these orphaned channels should fail the build, but in CI it is successful even with an orphaned channel.

## Actual Behavior

There are several orphaned channels in the existing code.

```
io.grpc.internal.ManagedChannelOrphanWrapper$ManagedChannelReference cleanQueue
SEVERE: *~*~*~ Previous channel ManagedChannelImpl{logId=37, target=directaddress:///9b8b79eb-09f7-483c-8801-ac1c9c047f62} was not shutdown properly!!! ~*~*~*
    Make sure to call shutdown()/shutdownNow() and wait until awaitTermination() returns true.
java.lang.RuntimeException: ManagedChannel allocation site
```

This muddy's the output, and can lead to confusion about what issue is a result of new code. I myself fell victim to seeing this issue and thinking it was due to my recently added code, only to find out that there are many orphaned channels from existing code.

## Steps to Reproduce the Problem

Run: `./mvnw -B test -q` locally & look at our CI, [example here](https://github.com/dapr/java-sdk/actions/runs/7623906031/job/20764920109#step:16:603).

**Comment by cicoyle** [comment]
I have 2 PRs to fix the orphaned channels in the following tests, there are still more!!

- [DaprClientGrpcTelemetryTest](https://github.com/dapr/java-sdk/pull/999)
- [GrpcChannelFacadeTest](https://github.com/dapr/java-sdk/pull/1000)

**Comment by mukundansundar** [comment]
another PR fixing NetworkUtilsTest https://github.com/dapr/java-sdk/pull/1007
