### ISSUE TITLE
Expand Metadata API

### ISSUE THREAD

**Issue by cicoyle** [dapr/java-sdk#1055]
Developers should be able to access metadata information (https://docs.dapr.io/reference/api/metadata_api/) from their Java applications. [This PR](https://github.com/dapr/java-sdk/pull/1049) has added support for some, but not all `metadata`. We should eventually support all `metadata`. [Please see this comment as to what is missing and should be added.](https://github.com/dapr/java-sdk/pull/1049#discussion_r1646293144)

**Comment by salaboy** [comment]
Following on this PR, we should add the details mentioned by @cicoyle https://github.com/dapr/java-sdk/pull/1049

**Comment by artur-ciocanu** [comment]
@salaboy and @cicoyle I am not sure how I could assign this issue to me, so it is clear that it is worked on.

**Comment by cicoyle** [comment]
I assigned you to the issue. Thx @artur-ciocanu - if you want to going forward plz try commenting `/assign` and daprbot should assign you to the issue, [like here](https://github.com/dapr/java-sdk/issues/1043#issuecomment-2117392653)

**Comment by artur-ciocanu** [comment]
> I assigned you to the issue. Thx @artur-ciocanu - if you want to going forward plz try commenting `/assign` and daprbot should assign you to the issue, [like here](https://github.com/dapr/java-sdk/issues/1043#issuecomment-2117392653)

Noted, thank you!
