### ISSUE TITLE
Update package dependencies with security vulnerabilities

### ISSUE THREAD

**Issue by alicejgibbons** [dapr/java-sdk#1081]
Packages with *High* security vulnerabilities in SDK version 1.11.0:

dapr-sdk-springboot:
- org.springframework spring-web-5.3.25 -> 6.1.5 [CWE-502](https://cwe.mitre.org/data/definitions/502.html) 
- org.springframework.boot spring-boot-autoconfigure 2.7.8 -> 3.3.1 [CWE-400](https://cwe.mitre.org/data/definitions/400.html)

dapr-sdk, dapr-sdk-springboot, dapr-sdk-actors:
- com.squareup.okio okio-2.8.0 -> 3.9.0 [CWE-681](https://cwe.mitre.org/data/definitions/681.html)
- org.jetbrains.kotlin kotlin-stdlib 1.4.10 -> 2.0.0 [CWE-667](https://cwe.mitre.org/data/definitions/667.html)

## Release Note

RELEASE NOTE: **UPDATE** Package dependencies.

**Comment by salaboy** [comment]
All these packages had been for the upcoming 1.12.0 release, as spring boot version was upgraded to 3.2.6.

`com.squareup.okio okio-2.8.0` and  `org.jetbrains.kotlin kotlin-stdlib 1.4.10` were removed.

**Comment by artur-ciocanu** [comment]
@alicejgibbons we have upgraded recently everything to Spring Boot 3.2+ and Spring Boot 3.3+ so we shouldn't have any high security vulnerabilities, but do let us know if you still see any offending dependencies and we will take care, otherwise we can mark this issue as resolved.

Thank you! 🙇

**Comment by alicejgibbons** [comment]
Thanks for your hard work @artur-ciocanu, closing as completed!
