### ISSUE TITLE
Is there a sample which uses the actor pattern?

### ISSUE THREAD

**Issue by ji11er** [dapr/java-sdk#11]
I wish I had a sample that uses the actor pattern.

**Comment by amanbha** [comment]
Currently there is no Java sample which uses Actor pattern, we will create a SDK with Actor runtime for Java similar to [dotnet-sdk](https://github.com/dapr/dotnet-sdk)

**Comment by ji11er** [comment]
I thought so. I got in touch with you via Ricardo, I wanna use dapr for the solution I have to build up. I would like to contribute to create the SDK. I already started with some classes but would need some support. Whom to contact?

**Comment by amanbha** [comment]
@ji11er You can work with me.

**Comment by amanbha** [comment]
> I thought so. I got in touch with you via Ricardo, I wanna use dapr for the solution I have to build up. I would like to contribute to create the SDK. I already started with some classes but would need some support. Whom to contact?

@ji11er You can work with me.

**Comment by ji11er** [comment]
@amanbha can we get somehow private messaging established?

I would start to create issues and also a WIP pull request, simply to clarify if the code style matches.

I'm using currently the dotnet sdk as a template, but I have a question. see the following snippet from the ActorProxy.cs:
`        /// <summary>
        /// Creates a proxy to the actor object that implements an actor interface.
        /// </summary>
        /// <typeparam name="TActorInterface">
        /// The actor interface implemented by the remote actor object.
        /// The returned proxy object will implement this interface.
        /// </typeparam>
        /// <param name="actorId">The actor ID of the proxy actor object. Methods called on this proxy will result in requests
        /// being sent to the actor with this ID.</param>
        /// <param name="actorType">
        /// Type of actor implementation.
        /// </param>
        /// <returns>Proxy to the actor object.</returns>
        public static TActorInterface Create<TActorInterface>(ActorId actorId, string actorType)
            where TActorInterface : IActor
        {
            return DefaultProxyFactory.CreateActorProxy<TActorInterface>(actorId, actorType);
        }
`
I can't find a definition of "TActorInterface", is it imported from the runtime env?

Any help would be appreciated.

Thanks

**Comment by amanbha** [comment]
Sure, please send me a  meeting invite at amanbha@microsoft.com and we can discuss

**Comment by ji11er** [comment]
I'll do so

**Comment by ji11er** [comment]
clear to me
