### ISSUE TITLE
Can't propagate trace headers with actors 

### ISSUE THREAD

**Issue by alicejgibbons** [dapr/java-sdk#1151]
## Expected Behavior

I should be able to use opentelemetry SDK to propagate trace headers from the actor client to server. 

## Actual Behavior

Today, providing a `traceparent` header in the actor client doesn't propagate to the actor server while using the latest version of Dapr (1.14.4) and the Java SDK. Additionally following the example [here](https://github.com/dapr/java-sdk/tree/master/examples/src/main/java/io/dapr/examples/tracing) still causes the actor client and actor server traces to show up with two separate trace IDs.

## Steps to Reproduce the Problem
Run actor client and actor server apps, and use the open telemetry SDK to propagate the trace header through from client -> server. Print the headers out on each side to see that they are different.

## Release Note

RELEASE NOTE: **FIX** Propagate traces in actors

**Comment by artursouza** [comment]
I got it to work without any SDK change, see this new test version: https://github.com/dapr/java-sdk/pull/1154/files#r1839036940

**Comment by alicejgibbons** [comment]
Closing this since there is a workaround as linked

**Comment by artursouza** [comment]
@alicejgibbons Not a workaround but an example on how it should work. The app needs to handle the tracing for it to be propagated.

**Comment by alicejgibbons** [comment]
Can we push this great example that you made into examples or something? https://github.com/dapr/java-sdk/tree/master/examples/src/main/java/io/dapr/examples/tracing ?
