### ISSUE TITLE
[Workflows] Rename `callSubWorkflow` to `callChildWorkflow`

### ISSUE THREAD

**Issue by olitomlinson** [dapr/java-sdk#1155]
The Java SDK uses the method name `callSubWorkflow` rather than `callChildWorkflow` in the [workflow context](https://github.com/dapr/java-sdk/blob/0b7a051b79c7a394e9bd4f57bd40778fb5f29897/sdk-workflows/src/main/java/io/dapr/workflows/WorkflowContext.java#L376)

The Dapr documentation refers to [child workflows](https://docs.dapr.io/developing-applications/building-blocks/workflow/workflow-features-concepts/#child-workflows) , so I would recommend that the Java SDK change the method name to `callChildWorkflow` for consistency.

**Comment by salaboy** [comment]
@olitomlinson ok.. PR created.. I will follow the tests to see if I am missing something. 
@artursouza do you know if we need to deprecate the old methods? Do you know how to create a release note for this change? It is a simple replace to upgrade to this new signature.
