### ISSUE TITLE
Steps to regenerate Protobuf classes

### ISSUE THREAD

**Issue by brunoborges** [dapr/java-sdk#13]
## Describe the proposal
What were the steps followed to generate the protobuf classes?

**Comment by artursouza** [comment]
I am new to this code base as well. I see you have a PR and it re-generated some protobuf code. Can you share some insights?

**Comment by artursouza** [comment]
I have changed the code to not version control the auto-generated files and copies the proto files instead. A simple compile task will generate the protobuf files. The documentation should be updated to reflect that and mention that to update the proto files, there should be a copy from dapr/dapr into this repo (maybe also create a maven task to download this automatically).

**Comment by brunoborges** [comment]
Using git submodules is not ideal as it requires constant update of the commit hash where the submodule refers to.

A task to download may be the best solution, unless the protobuf generator can consume remote URLs

**Comment by artursouza** [comment]
I had discussed this with some folks. The Java proto files might be behind the master proto intentionally. The scenario is the one we have now where there is a breaking change in master branch but it is still not stable yet. We might need to download from a release branch to kind of guarantee an immutable proto file.

**Comment by artursouza** [comment]
It should be possible to automatically download the file from a URL. Then we just need to point to a file within a given commit ref in the URL and we have an immutable file to download from and have consistent behavior of the build pipeline.

@JuanJose-Herrera is looking into this now.

**Comment by artursouza** [comment]
We will merge the PR to automatically download the proto from dapr/dapr repo - we are just waiting for milestone 0.4 to be released this week.
