### ISSUE TITLE
Test .net SDK with Java SDK for Actor methods

### ISSUE THREAD

**Issue by artursouza** [dapr/java-sdk#185]
## Expected Behavior

1. Actor in .Net calls method on Actor in Java for String type.
2. Actor in .Net calls method on Actor in Java for Integer type.
3. Actor in .Net calls method on Actor in Java for Class type.
4. Actor in Java calls method on Actor in .Net for String type.
5. Actor in Java calls method on Actor in .Net for Integer type.
6. Actor in Java calls method on Actor in .Net for Class type.

**Comment by LMWF** [comment]
Clarification - in the list above, the type indicated is the type for both input and output.

**Comment by LMWF** [comment]
These work as expected other than for the case where the input is a string type.  That scenario encounters the known extra pair of quotes issue.
