### ISSUE TITLE
[java-sdk] Adds checkstyle and bug finder

### ISSUE THREAD

**Issue by artursouza** [dapr/java-sdk#19]
* Adds a checkstyle to Java SDK and make build fail due to style violations.
* Adds [SpotBugs](https://spotbugs.github.io/) and make build fail due to violations.
* Fixes existing violations.
* Generated code should be excluded from static analysis.

**Comment by yaron2** [comment]
Can we close this?

**Comment by LMWF** [comment]
Checkstyle is done, static analysis is not complete (spot bugs).
