### ISSUE TITLE
Remove Maven dependency to run dapr for examples

### ISSUE THREAD

**Issue by artursouza** [dapr/java-sdk#200]
`dapr run` commands do not invoke `mvn` anymore and use `java -jar fatjar.jar` instead. It means the install command should generate a fatjar for examples.

**Comment by yaron2** [comment]
> I would like to look at this. Can I give it a go?

Sure

**Comment by yaron2** [comment]
@Rinita-De you're now assigned :)

**Comment by artursouza** [comment]
The fatjar has a single main class, so there will probably be a shared main class for all examples. The first argument could be the class of the example being run and the remaining args can be forwarded to the example class’s “main” function.

**Comment by yaron2** [comment]
Will close this: https://github.com/dapr/java-sdk/issues/181

**Comment by Rinita-De** [comment]
Thanks for all the information given on the issue. I have done the following as per the suggestions

1) Created a new class file "DaprMainApplication". It takes requires mainClass as a mandatory Command line argument, args is optional. Based on mainClass it calls the main method
2) POM file updated to create fat jar and points to DaprMainApplication as mainCalss

The command to run Service and client for actor looks as follows now

```
dapr run --app-id demoactorservice --app-port 3000 --port 3005 -- java -jar dapr-sdk-examples-0.2.0-SNAPSHOT-exec.jar --mainClass=io.dapr.examples.actors.http.DemoActorService --args="-p 3000"

dapr run --app-id demoactorclient --app-port 3000 --port 3006 -- java -jar dapr-sdk-examples-0.2.0-SNAPSHOT-exec.jar --mainClass=io.dapr.examples.actors.http.DemoActorClient 
```

If this looks okay, I will update the Readme files for all the examples as well.

**Comment by artursouza** [comment]
That works for me too. I was thinking of another way:
```
dapr run --app-id demoactorservice --app-port 3000 --port 3005 -- java -jar dapr-sdk-examples-0.2.0-SNAPSHOT-exec.jar io.dapr.examples.actors.http.DemoActorService -p 3000

dapr run --app-id demoactorclient --app-port 3000 --port 3006 -- java -jar dapr-sdk-examples-0.2.0-SNAPSHOT-exec.jar io.dapr.examples.actors.http.DemoActorClient
```

`DaprMainApplication` would simply consume the first argument as the main class and forward the remaining arg[] to the given class' main function.

To be honest, either way works for me. Your approach if self documented while the one I mentioned is less verbose.

**Comment by artursouza** [comment]
I tested with the http invoke example. Thanks a lot for this, @Rinita-De !

**Comment by yaron2** [comment]
Thanks for your contribution.
