### ISSUE TITLE
SpringBoot as first class integration

### ISSUE THREAD

**Issue by RicardoNiepel** [dapr/java-sdk#206]
## Describe the proposal

It would be awesome to have a first-class SpringBoot integration.
As first steps this could include
- Moving springboot classes out of examples and put these into separate library (like it was done with [Dapr.AspNetCore](https://github.com/dapr/dotnet-sdk/tree/master/src/Dapr.AspNetCore))
- Adding Dapr annotations, like `@Topic("message")` and generating "/dapr/subscribe" response automatically (like it was done at[dotnet-sdk/AspNetCore/ControllerSample/](https://github.com/dapr/dotnet-sdk/blob/master/samples/AspNetCore/ControllerSample/Controllers/SampleController.cs))

**Comment by artursouza** [comment]
We had springboot integration as an additional jar. It was decided in the design reviews not to include dependency to springboot. So we moved it into examples instead. We can revisit this decision for future milestones based on customer feedback.
