### ISSUE TITLE
Invoke GRPC sample arguments

### ISSUE THREAD

**Issue by RicardoNiepel** [dapr/java-sdk#207]
[HelloWorldService.java](https://github.com/dapr/java-sdk/blob/master/examples/src/main/java/io/dapr/examples/invoke/grpc/HelloWorldService.java) has the follwing
```sh
dapr run --app-id hellogrpc --app-port 5000 --protocol grpc \
 *   -- mvn exec:java -pl=examples -D exec.mainClass=io.dapr.examples.invoke.grpc.HelloWorldService \
 *   -D exec.args="-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5009"
```

the readme only mentions
```sh
dapr run --app-id hellogrpc --app-port 5000 --protocol grpc \
*  -- mvn exec:java -pl=examples -D exec.mainClass=io.dapr.examples.invoke.grpc.HelloWorldService \
*  -D exec.args="-p 5000"
```

Do we need the additional args for GRPC?

**Comment by artursouza** [comment]
The additional arguments are for debugging. They are not needed. We should fix the comment to not include debugging arguments.
