### ISSUE TITLE
[java-sdk] Create Dapr's HTTP Client

### ISSUE THREAD

**Issue by artursouza** [dapr/java-sdk#21]
NEW SCOPE:
Manually create http client for Dapr's APIs.

OLD SCOPE:
* Auto-generate http client from Dapr's OpenAPI definition (https://swagger.io/specification/)
* If needed, create OpenAPI definition in Dapr/dapr to seed auto-generation for any language.

**Comment by amanbha** [comment]
Linking to https://github.com/dapr/dapr/issues/16

For now, we can handcraft the http calls as we have few http calls. Autogenerated ones will need to be wrapped.

**Comment by artursouza** [comment]
It seems that we don't have the OpenAPI specs ready to complete this task.

**Comment by artursouza** [comment]
I have changed the scope of this task to not use the auto-generated version since we don't have service API specs for that yet. It can be simply be manually created right now.

**Comment by mestizoLopez** [comment]
Can you assign me please?
