### ISSUE TITLE
dapr vs daprd - Debug Java application or Dapr's Java SDK

### ISSUE THREAD

**Issue by RicardoNiepel** [dapr/java-sdk#212]
It's currently documented to use ```dapr``` to debug Dapr Java applications.

Looking into [Configuring Visual Studio Code for debugging with daprd](https://github.com/dapr/docs/tree/master/howto/vscode-debugging-daprd) shows the usage of ```daprd``` in debugging scenarios.

Any reason we cannot use daprd also for Java / for doing it differently?

**Comment by artursouza** [comment]
You can use both ways. This is not specific to Java. As you pointed out, the other solution is for Visual Studio Code while this one is for any IDE.

daprd is invoked by dapr. There is significant logic in order to prepare all arguments to invoke daprd directly. Using dapr cli abstracts this logic.

**Comment by RicardoNiepel** [comment]
Maybe we can just change to ```daprd```?

This would eleminate the need for dummy commands and different instructions for Unix and Windows

**Comment by youngbupark** [comment]
@RicardoNiepel `dapr cli` is designed for development purpose. it finds free grpc and http ports when you develop multiple apps. maybe it is better to allow dapr cli to run alone without app. 

cc/ @msfussell @yaron2 @amanbha

**Comment by RicardoNiepel** [comment]
This would be a great idea and eliminate the dummy commands/OS differences in calling it
