### ISSUE TITLE
Set tryReflectionSetAccessible to disabled for Netty

### ISSUE THREAD

**Issue by yaron2** [dapr/java-sdk#220]
As described in https://github.com/dapr/java-sdk/issues/219, a pretty verbose exceptions log stream are outputted and may confuse users.

The solution as proposed [here](https://github.com/netty/netty/issues/7817) is to put the following config option:
```
-Dio.netty.tryReflectionSetAccessible=true
```

**Comment by artursouza** [comment]
Closing this since reducing verbosity solved the problem.
