### ISSUE TITLE
Guidance of IntelliJ setup

### ISSUE THREAD

**Issue by RicardoNiepel** [dapr/java-sdk#231]
## Describe the proposal

As IntelliJ is one of the main and most popular Java IDEs, it would be create to have a guidance, how the best setup/configuration of IntelliJ should be for developing, executing and debugging Dapr applications in Java.

At the end this would be very similar to the existing [Configuring Visual Studio Code for debugging with daprd](https://github.com/dapr/docs/tree/master/howto/vscode-debugging-daprd) docs.

**Comment by artursouza** [comment]
See updated debug instructions in https://github.com/dapr/java-sdk, or go directly to https://github.com/dapr/docs/tree/master/howto/intellij-debugging-daprd
