### ISSUE TITLE
[java-sdk] Create ActorProxy

### ISSUE THREAD

**Issue by artursouza** [dapr/java-sdk#24]
1.	Create the ActorProxy methods on the Java SDK, modeling it after the [Dotnet proxy](https://github.com/dapr/dotnet-sdk/blob/master/src/Dapr.Actors/Client/ActorProxy.cs). It should only implement non remoting invocation methods, basically all InvokeAsync. Non remoting invocation is [explained here ](https://github.com/dapr/dotnet-sdk/blob/master/docs/get-started-dapr-actor.md#invoke-actor-method-without-actor-service-remoting)

**Comment by ji11er** [comment]
can you assign it to me?

**Comment by JuanJose-Herrera** [comment]
Hi All, I will start to work in the ActorProxy methdos
