### ISSUE TITLE
Distributed tracing: How should I?

### ISSUE THREAD

**Issue by cero-t** [dapr/java-sdk#244]
I tried distributed tracing using Java SDK, Zipkin, and Dapr, but I couldn't.

When I passed the "x-correlation-id" to the other service running on Dapr using RestTemplate via HTTP header, they were well distributed traced.
But when I tried same thing using DaprClientHttp via metadata, the correlation id wasn't passed.

Here's code snipet using DaprClient which doesn't work.
```
DaprClient client = new DaprClientBuilder().build();
Map<String, String> metadata = Map.of("x-correlation-id", corId);
client.invokeService(Verb.POST, "example1", "someMethod", Map.of("message", "Hello world"), metadata)
        .block();
client.invokeService(Verb.GET, "example1", "someMethod", metadata, Map.class)
        .block();
```

And here's code snipet using RestTemplate which works fine.
```
// (There're given corId)
HttpHeaders headers = new HttpHeaders();
headers.add("x-correlation-id", corId);
var entity = new HttpEntity<>(Map.of("message", "Hello world"), headers);

restTemplate.exchange(baseUrl + "/invoke/example1/method/someMethod",
        HttpMethod.POST, entity, Void.class);

restTemplate.exchange(baseUrl + "/invoke/example1/method/someMethod",
        HttpMethod.GET, new HttpEntity<>(headers), Map.class).getBody();
```

Both of above works fine as functions but the former one doesn't propagate the correlation id to example1's someMethod.

In any case, I don't think the correct way is to use metadata to propagate the correlation id, and adding metadata as an argument to the saveState method or getState method of DaprClient class might be cumbersome.
Is there any good way to improve the Java SDK for distributed tracing? For example, it would be nice to have a mechanism to store and retrieve correlation id in a specific thread local context or something like MDC.

**Comment by artursouza** [comment]
Thanks for reporting the bug.

I do agree that we need a better way to handle distributed tracing in the Java SDK. Regarding thread context, it can be used but I wonder how it would work in the context of a Rector chain.

**Comment by cero-t** [comment]
Thank you for answering. As you mentioned, thread context doesn't work in the Reactor chain.
But as far as I confirmed, when I used Spring WebFlux and Spring Cloud Sleuth I could get the correct correlation id from the thread context (MDC) in the Reactor Chain. I haven't read the code enught, but I guess that these are the implementations that pass the correlation id from the parent thread context to the reactor's sub thread context.

https://github.com/spring-cloud/spring-cloud-sleuth/blob/master/spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/annotation/ReactorSleuthMethodInvocationProcessor.java

https://github.com/spring-cloud/spring-cloud-sleuth/tree/master/spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/reactor

Although it uses spring container to insert the additional processing, I think we can do the similar thing without spring.

**Comment by cero-t** [comment]
I found that Hooks#onEachOperator can be used to add interceptor.

https://github.com/spring-cloud/spring-cloud-sleuth/blob/master/spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/reactor/TraceReactorAutoConfiguration.java#L156

https://projectreactor.io/docs/core/release/api/reactor/core/publisher/Hooks.html#onEachOperator-java.util.function.Function-

And here's a blog that explains about it with some simple sample codes.
http://ttddyy.github.io/mdc-with-webclient-in-webmvc/

**Comment by youngbupark** [comment]
> In any case, I don't think the correct way is to use metadata to propagate the correlation id, and adding metadata as an argument to the saveState method or getState method of DaprClient class might be cumbersome.
> Is there any good way to improve the Java SDK for distributed tracing? For example, it would be nice to have a mechanism to store and retrieve correlation id in a specific thread local context or something like MDC.

@cero-t To clarify your requests, 

1. invokeService API doesn't propagate correlation id properly, but it works when passing x-corrleation-id header to dapr http service invocation api without java-sdk. (Dapr sidecar is processing correlation-id header properly)
2. You want to have a way to propagate correlation id to save/getState or any other Dapr APIs with JAVA-SDK
3. You want to have a way to get the propagated correlation id in the response to track the span with JAVA-SDK

cc/ @artursouza

**Comment by cero-t** [comment]
@youngbupark Thank you for replying!

> invokeService API doesn't propagate correlation id properly, but it works when passing x-corrleation-id header to dapr http service invocation api without java-sdk. (Dapr sidecar is processing correlation-id header properly)

Exactly.

> You want to have a way to propagate correlation id to save/getState or any other Dapr APIs with JAVA-SDK

Yes I do.

> You want to have a way to get the propagated correlation id in the response to track the span with JAVA-SDK

I want to have a way to pass the correlation ID to a request.
Assuming that the correlation ID is already obtained from the HTTP header, I want to pass it when invoking other services.

I want write code like this.
```
String corId = // obtain from HTTP headers in different ways for each framework
DaprContext.getCurrentContext().setCorrelationId(corId);
```

And after that, I want the correlation ID to be set on the http request header, when I call invokeService or saveState, getState, publish, etc.

Did I answer your question correctly?

**Comment by youngbupark** [comment]
Thanks for the clarification. Let's be more specific for the last question.

I can come up with two possible scenarios based on your comments.

1. AppA is http server exposing to external. AppA gets http requests with Correlation ID as a http server and AppA calls saveState to save the state with the received Correlation ID.

2. You have AppA and AppB. AppA invokes AppB to save the state by AppB.

So the expected call-flow will be
```
AppA invoke AppB(pass COR_ID_1 via http request) -> Dapr sidecar for AppA -----call---> Dapr sidecar for AppB -> AppB gets COR_ID_1 via http request -> AppB calls saveState() with COR_ID_1 -> Dapr sidecar for AppB saves the state with COR_ID_1
```

I assume you described the first scenario. We need to file two different issues in dapr/dapr and dapr/java-sdk repos respectively to support either the first or the second scenario. I will follow it up.

**Comment by youngbupark** [comment]
@cero-t JFYI - We're improving service invocation and tracing behaviors in this milestone. Once we finish this milestone, you can trace state, service invocation, publish by passing your own correlation id. We will write the docs to show how to correlate user app's trace with sidecar traces.

Related work items:
https://github.com/dapr/dapr/issues/1409
https://github.com/dapr/dapr/issues/1317
https://github.com/dapr/dapr/issues/1371
https://github.com/dapr/dapr/issues/1373

cc/ @shalabhms @yaron2 @amanbha @msfussell @orizohar

**Comment by cero-t** [comment]
Great!! I'll try it. Thanks!

**Comment by artursouza** [comment]
@cero-t 

We have recently merged code to support W3C tracing in the Java SDK for Dapr. The application code is still responsible for instrumentation but the W3C headers will be propagated in Dapr. See the merged code below, it will be in the next Dapr release (0.11 runtime, 0.9 Java SDK).

https://github.com/dapr/java-sdk/pull/320

**Comment by cero-t** [comment]
@artursouza 
Thank you! I'll try it out as soon as it's released.

**Comment by artursouza** [comment]
@cero-t You can try the unreleased version if you want: 0.9.0-SNAPSHOT

**Comment by cero-t** [comment]
@artursouza oh thanks, I'll try this weekend!;D

**Comment by msfussell** [comment]
@cero-t Did you try this out and are you good?

**Comment by artursouza** [comment]
Closing this issue. Please, use SDK version 0.9.0 or greater to use W3C tracing.
