### ISSUE TITLE
[sample] Add sample for Actors

### ISSUE THREAD

**Issue by artursouza** [dapr/java-sdk#25]
Create a sample (in dapr/java-sdk) showing all features of Actors in Java:

1.	Once all features for Actors in Dapr’s Java SDK are available, implement a sample showing how to use all Actor features. Sample using the SDK will be in this repo.
2.	Add documentation, so users can execute in Windows, Linux and MacOS.
3.	Add the original files used to generate any image, so external contributors can update documentation in the future.

**Comment by amanbha** [comment]
Let's keep Java samples using the SDK  in java-sdk repo. Language specific samples using SDKs will be in their respective repos. C# samples using SDKs are in dotnet-sdk.repo.
It would be easier to maintain in single repo when API breaking changes are introduced and they remain correctly versioned.

**Comment by marcosreyes05** [comment]
I can help

**Comment by artursouza** [comment]
Existing example works with timer, reminder, method invocation. We need to state state (put and get). Add documentation. Move it outside http folder.
