### ISSUE TITLE
Dapr sidecar does not contain subscribed topics provided by java app

### ISSUE THREAD

**Issue by pagufler** [dapr/java-sdk#266]
## Expected Behavior
Dapr sidcar of app shows in container logs the array with the subscribed topics. This would mean: events from subscribed topics are retrieved by java application.

## Actual Behavior
Events are not provided to the java application. 
The dapr sidecar logs show following logs:

> time="2020-04-03T13:47:47.693907425Z" level=info msg="starting Dapr Runtime -- version 0.5.0 -- commit v0.3.0-rc.0-157-gb3bcd88" app_id=<app-id> instance=<podid> scope=dapr.runtime type=log ver=0.5.0
> time="2020-04-03T13:47:47.694047726Z" level=info msg="log level set to: debug" app_id=<app-id> instance=<podid> scope=dapr.runtime type=log ver=0.5.0
> time="2020-04-03T13:47:47.694762231Z" level=info msg="metrics server started on :9090/" app_id=<app-id> instance=<podid> scope=dapr.metrics type=log ver=0.5.0
> time="2020-04-03T13:47:47.712423472Z" level=info msg="kubernetes mode configured" app_id=<app-id> instance=<podid> scope=dapr.runtime type=log ver=0.5.0
> time="2020-04-03T13:47:47.712645473Z" level=info msg="dapr id: <app-id>" app_id=<app-id> instance=<podid> scope=dapr.runtime type=log ver=0.5.0
> time="2020-04-03T13:47:47.712816975Z" level=info msg="mTLS enabled. creating sidecar authenticator" app_id=<app-id> instance=<podid> scope=dapr.runtime type=log ver=0.5.0
> time="2020-04-03T13:47:47.713296478Z" level=info msg="trust anchors extracted successfully" app_id=<app-id> instance=<podid> scope=dapr.runtime.security type=log ver=0.5.0
> time="2020-04-03T13:47:47.71347548Z" level=info msg="authenticator created" app_id=<app-id> instance=<podid> scope=dapr.runtime type=log ver=0.5.0
> time="2020-04-03T13:47:47.723036856Z" level=info msg="found component messagebus (pubsub.azure.servicebus)" app_id=<app-id> instance=<podid> scope=dapr.runtime type=log ver=0.5.0
> time="2020-04-03T13:47:47.723328058Z" level=info msg="application protocol: http. waiting on port 8080" app_id=<app-id> instance=<podid> scope=dapr.runtime type=log ver=0.5.0
> time="2020-04-03T13:48:29.053883659Z" level=info msg="application discovered on port 8080" app_id=<app-id> instance=<podid> scope=dapr.runtime type=log ver=0.5.0
> time="2020-04-03T13:48:29.305592656Z" level=warning msg="either no actor state store or multiple actor state stores are specified in the configuration, actor stores specified: 0" app_id=<app-id> instance=<podid> scope=dapr.runtime type=log ver=0.5.0
> **time="2020-04-03T13:48:29.31612004Z" level=info msg="App is subscribed to the following topics: []" app_id=<app-id> instance=<podid> scope=dapr.runtime type=log ver=0.5.0**
> time="2020-04-03T13:48:29.31617134Z" level=info msg="Initialized service discovery to kubernetes" app_id=<app-id> instance=<podid> scope=dapr.runtime type=log ver=0.5.0
> time="2020-04-03T13:48:29.316216941Z" level=warning msg="actors: state store must be present to initialize the actor runtime" app_id=<app-id> instance=<podid> scope=dapr.runtime.actor type=log ver=0.5.0
> time="2020-04-03T13:48:29.316246741Z" level=warning msg="failed to init actors: state store does not support transactions which actors require to save state - please see https://github.com/dapr/docs" app_id=<app-id> instance=<podid> scope=dapr.runtime type=log ver=0.5.0
> time="2020-04-03T13:48:29.316481143Z" level=info msg="enabled metrics grpc middleware" app_id=<app-id> instance=<podid> scope=dapr.runtime.grpc type=log ver=0.5.0
> time="2020-04-03T13:48:29.316517043Z" level=info msg="sending workload csr request to sentry" app_id=<app-id> instance=<podid> scope=dapr.runtime.grpc type=log ver=0.5.0
> time="2020-04-03T13:48:29.367156045Z" level=info msg="certificate signed successfully" app_id=<app-id> instance=<podid> scope=dapr.runtime.grpc type=log ver=0.5.0
> time="2020-04-03T13:48:29.368351755Z" level=info msg="gRPC server is running on port 50001" app_id=<app-id> instance=<podid> scope=dapr.runtime type=log ver=0.5.0
> time="2020-04-03T13:48:29.368403855Z" level=info msg="starting workload cert expiry watcher. current cert expires on: 2020-04-04 14:03:29 +0000 UTC" app_id=<app-id> instance=<podid> scope=dapr.runtime.grpc type=log ver=0.5.0
> time="2020-04-03T13:48:29.368701957Z" level=info msg="enabled cors http middleware" app_id=<app-id> instance=<podid> scope=dapr.runtime.http type=log ver=0.5.0
> time="2020-04-03T13:48:29.368739458Z" level=info msg="enabled proxy http middleware" app_id=<app-id> instance=<podid> scope=dapr.runtime.http type=log ver=0.5.0
> time="2020-04-03T13:48:29.368755858Z" level=info msg="enabled metrics http middleware" app_id=<app-id> instance=<podid> scope=dapr.runtime.http type=log ver=0.5.0
> time="2020-04-03T13:48:29.368775358Z" level=info msg="http server is running on port 3500" app_id=<app-id> instance=<podid> scope=dapr.runtime type=log ver=0.5.0
> time="2020-04-03T13:48:29.368796758Z" level=info msg="dapr initialized. Status: Running. Init Elapsed 41656.374987ms" app_id=<app-id> instance=<podid> scope=dapr.runtime type=log ver=0.5.0

In the pod we have the dapr container and the app container. We added an additional container in the pod (in order to do curl commands) and called the java app endpoint:
`curl GET http://10.240.0.85:8080/<appid>/dapr/subscribe`
that returned:
`["topic.app.apptopic-request","app.create","app.update","app.delete"]`

The logs above are from AKS environment. We restarted the dapr-system pods, also the app pod, but the dapr sidecar of the app has still no subscription to topics although the app returns on the corresponding REST endpoint the required topics to subscribe

We tested the collaboration between the apps first on localhost with the same code, there it works as it should:
- app 1: publishes on topic1 a msg
- app 2: is subscribed to topic 1 and retrieves the event, when app 1 has published the msg

Please let us know what we should try / check in order to get this running on the server.
Thanks

**Comment by artursouza** [comment]
Hi @pagufler,

Please, change the controller to response to the following API instead: `GET http://10.240.0.85:8080/dapr/subscribe` - there should be no `appid` in the path.

**Comment by pagufler** [comment]
Hi @artursouza,
ah, that was the problem. We knew it must be something small, but did not see it.
Thank you! Now the application gets the event
