### ISSUE TITLE
Protobuf client update for java-sdk

### ISSUE THREAD

**Issue by youngbupark** [dapr/java-sdk#272]
## Describe the proposal

This is to update protobuf client along with https://github.com/dapr/dapr/issues/1409

**Comment by youngbupark** [comment]
@artursouza can you please work on this ? 

cc/ @LMWF

**Comment by artursouza** [comment]
Yes.

**Comment by youngbupark** [comment]
> Yes.

Thanks!

**Comment by youngbupark** [comment]
@artursouza Thanks for taking this. We have introduced DataWithContentType to specify the content_type. We're using Protobuf `Any` in a wrong way. basically, this is designed for holding serialized protobuf message. technically, we should not pass raw byte array to Any.Value.

Also if calleapp is http based, then dapr will return `DataWithContentType`. So we always need to check this type (this is new one). 

You can see the example:
https://github.com/dapr/python-sdk/blob/5a2e43fbd2fc07e553cd3ab9f8c4901642f7d112/examples/invoke-simple/invoke-caller.py#L19-L38

**Comment by amanbha** [comment]
The changes in java sdk are needed to handle new proto
