### ISSUE TITLE
Update pub/sub subscription

### ISSUE THREAD

**Issue by yaron2** [dapr/java-sdk#278]
We need to update the pub/sub code for subscriptions to match the new subscription JSON structure.

Reference: https://github.com/dapr/dapr/issues/1518#issuecomment-624765422

**Comment by artursouza** [comment]
Breaking change for next milestone.

**Comment by youngbupark** [comment]
this work depends on https://github.com/dapr/java-sdk/issues/284

**Comment by amanbha** [comment]
> this work depends on #284

@youngbupark These should be independent.

**Comment by artursouza** [comment]
They are dependent because the SDK does not work with master as of now. And this issue will also block the SDK from working completely with 0.8. The changes to make the SDK compatible with 0.8 will need to be merged together. Getting the proto files right is the first step.

**Comment by amanbha** [comment]
> They are dependent because the SDK does not work with master as of now. And this issue will also block the SDK from working completely with 0.8. The changes to make the SDK compatible with 0.8 will need to be merged together. Getting the proto files right is the first step.

Sure as a whole for SDK, they both are needed, but they are not dependent. #284 is for actors which doesn't need proto.

**Comment by youngbupark** [comment]
@artursouza can we create feature branch ?  I might point it out wrong number - https://github.com/dapr/java-sdk/issues/283. this depends on #283 , not #284. looks like @wcs1only is assigned to #283 as well..
