### ISSUE TITLE
Samples really working? - Build with Java 11, rest is build with Java 8

### ISSUE THREAD

**Issue by JMayrbaeurl** [dapr/java-sdk#279]
## Expected Behavior

Running Method invocation sample as described [here](https://github.com/dapr/java-sdk/tree/master/examples/src/main/java/io/dapr/examples/invoke/http)

## Actual Behavior

DemoService crashes on start with UnsupportedClassVersionError exception:
`dapr run --app-id invokedemo --app-port 3004 --port 3005 -- java -jar examples/target/dapr-java-sdk-examples-exec.jar io.dapr.examples.invoke.http.DemoService -p 3004
Starting Dapr with id invokedemo. HTTP Port: 3005. gRPC Port: 56180
←[94;1m== APP == Exception in thread "main" java.lang.UnsupportedClassVersionError: io/dapr/springboot/DaprMainApplication has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
←[0m
←[94;1m== APP ==        at java.lang.ClassLoader.defineClass1(Native Method)
←[0m
←[94;1m== APP ==        at java.lang.ClassLoader.defineClass(Unknown Source)
←[0m
←[94;1m== APP ==        at java.security.SecureClassLoader.defineClass(Unknown Source)
←[0m
←[94;1m== APP ==        at java.net.URLClassLoader.defineClass(Unknown Source)
←[0m
←[94;1m== APP ==        at java.net.URLClassLoader.access$100(Unknown Source)
←[0m
←[94;1m== APP ==        at java.net.URLClassLoader$1.run(Unknown Source)
←[0m
←[94;1m== APP ==        at java.net.URLClassLoader$1.run(Unknown Source)
←[0m
←[94;1m== APP ==        at java.security.AccessController.doPrivileged(Native Method)
←[0m
←[94;1m== APP ==        at java.net.URLClassLoader.findClass(Unknown Source)
←[0m
←[94;1m== APP ==        at java.lang.ClassLoader.loadClass(Unknown Source)
←[0m
←[94;1m== APP ==        at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:92)
←[0m
←[94;1m== APP ==        at java.lang.ClassLoader.loadClass(Unknown Source)
←[0m
←[94;1m== APP ==        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:46)
←[0m
←[94;1m== APP ==        at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
←[0m
←[94;1m== APP ==        at org.springframework.boot.loader.Launcher.launch(Launcher.java:51)
←[0m
←[94;1m== APP ==        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:52)
←[0m
←[93;1m== DAPR == time="2020-05-07T14:40:52.5638737+02:00" level=info msg="starting Dapr Runtime -- version 0.7.0 -- commit 57bd1e6" app_id=invokedemo instance=vie-juergenma01 scope=dapr.runtime type=log ver=0.7.0`

## Steps to Reproduce the Problem

Just following official documentation [here](https://github.com/dapr/java-sdk/tree/master/examples/src/main/java/io/dapr/examples/invoke/http)

The reason is that the 'examples' Maven module is build targeting Java 11 and the rest of the project is using Java 8. Simple setting the release property to 8 in the pom.xml file fixes this. Do you want to have a PR?

**Comment by artursouza** [comment]
We want to validate that the SDK is built with Java 8 and apps can use it with Java 11.

BTW, the PR above is doing much more than fixing the issue. Let me repro this.

**Comment by artursouza** [comment]
I could not reproduce the issue and the sample for http call worked for me:
```
ℹ️  Updating metadata for app command: java -jar examples/target/dapr-java-sdk-examples-exec.jar io.dapr.examples.invoke.http.DemoService -p 3000
✅  You're up and running! Both Dapr and your app logs will appear here.


== APP == Server: "message one" @ 2020-05-11 21:05:48.538 and metadata: {"user-agent":"grpc-java-netty/1.25.0","host":"127.0.0.1:3000","content-type":"application/json","content-length":"13","dapr-authority":"127.0.0.1:49544","dapr-grpc-accept-encoding":"gzip","traceparent":"00-057331356871f86551e949872d839552-10072ede5ad158cf-00"}

== APP == Server: "message two" @ 2020-05-11 21:05:49.585 and metadata: {"user-agent":"grpc-java-netty/1.25.0","host":"127.0.0.1:3000","content-type":"application/json","content-length":"13","dapr-grpc-accept-encoding":"gzip","dapr-authority":"127.0.0.1:49544","traceparent":"00-192f781c6f78b5e9f1c4540b500ab38c-afcaccd5be4fa9b7-00"}

^Cℹ️
terminated signal received: shutting down
== DAPR == time="2020-05-11T21:05:52.68605-07:00" level=info msg="dapr shutting down. Waiting 5 seconds to finish outstanding operations" app_id=invokedemo instance=WU2TEHPV03CX-03.Redmond.corp.microsoft.com scope=dapr.runtime type=log ver=0.7.0

✅  Exited Dapr successfully
== DAPR == time="2020-05-11T21:05:52.686118-07:00" level=info msg="stop command issued. Shutting down all operations" app_id=invokedemo instance=WU2TEHPV03CX-03.Redmond.corp.microsoft.com scope=dapr.runtime type=log ver=0.7.0

✅  Exited App successfully
[21:05:52] ~/code/dapr/java-sdk (master)
$ java -version
java version "13.0.1" 2019-10-15
Java(TM) SE Runtime Environment (build 13.0.1+9)
Java HotSpot(TM) 64-Bit Server VM (build 13.0.1+9, mixed mode, sharing)
```

Which JDK are you using?

**Comment by JMayrbaeurl** [comment]
Sorry. I've recently installed an Oracle 8 Java SDK for testing purposes and on installation the path to this installation was automatically added to my path variable:

`C:\Program Files (x86)\Common Files\Oracle\Java\javapath>java.exe -version
java version "1.8.0_241"
Java(TM) SE Runtime Environment (build 1.8.0_241-b07)
Java HotSpot(TM) 64-Bit Server VM (build 25.241-b07, mixed mode)`

And since the complete project is targeted at version 8, I assumed the samples are too. Obvisouly I've not read the comment about using Java 11 for the examples in the documentation.
After changing the path variable to point to a Java 14 SDK installation everything worked correctly:

`C:\>java -version
openjdk version "14.0.1" 2020-04-14
OpenJDK Runtime Environment AdoptOpenJDK (build 14.0.1+7)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 14.0.1+7, mixed mode, sharing)`

By the way. Is there a way to control the Java environment, that's used by the dapr CLI?

**Comment by artursouza** [comment]
Dapr CLI has no idea about JVM. You can change JDK in your env by changing env variables PATH and JAVA_HOME

**Comment by JMayrbaeurl** [comment]
I know this. But messing around with env variables PATH and/or JAVA_HOME on systems that have multiple JREs installed, is really cumbersome.

**Comment by artursouza** [comment]
I agree. Will jenv help? https://www.jenv.be

**Comment by JMayrbaeurl** [comment]
I think jenv doesn't work on Windows
