### ISSUE TITLE
Rename maven module 'sdk-springboot' to 'sdk-spring'

### ISSUE THREAD

**Issue by JMayrbaeurl** [dapr/java-sdk#280]
## Describe the proposal
Since the existing module 'sdk-springboot' doesn't use Spring Boot, rename it to 'sdk-spring' and add a new module for Spring Boot support like autostarters.

**Comment by artursouza** [comment]
I am OK with this change. Please, submit a PR with the rename.

**Comment by artursouza** [comment]
Issue https://github.com/dapr/java-sdk/issues/281 can be done in this jar, so no renaming would be needed.

**Comment by JMayrbaeurl** [comment]
The basic idea of renaming was to remove the confusion on the 'sdk-springboot' module. It offers no direct Spring Boot support, but simple Spring support. There renaming to 'sdk-spring' makes sense to me. And by introducing a dedicated module for Spring Boot support 'dapr-spring-boot' there's a clear approach for the offered support. I think it's a good idea to offer a Dapr SDK for simple Spring support and an additional one, based on this, for Spring Boot support.

**Comment by artursouza** [comment]
We are keeping our footprint small for Spring. Adding more modules goes against that. Can you make a case to review with the team on why we should add more support to Spring? Real customer scenarios can help make a point here.

**Comment by JMayrbaeurl** [comment]
Just started with the renaming, but figured out that the verb 'springboot' is spread over the complete project, used in examples module, sdk-test module and so on. All these changes would need a lot of testing that's currently not covered by the included tests. The Gradle build setup is still on the recent 0.5.x version, and therefore makes changes impossible too
