### ISSUE TITLE
Provide Spring Boot starter

### ISSUE THREAD

**Issue by JMayrbaeurl** [dapr/java-sdk#281]
## Describe the proposal
Provide a Spring Boot starter that adds a fully configured DaprClient instance to the application context by just putting the starter artifact in the dependency list of Maven (pom.xml file)

**Comment by artursouza** [comment]
I saw the PR, can this be done without adding all the new jars? Can this be done in the existing sdk-springboot package?

**Comment by JMayrbaeurl** [comment]
No. Because the basic idea is to rename the existing 'sdk-springboot' package to 'sdk-spring' for generic Spring support and introduce a new one for Spring Boot support. For the implementation I've followed the guidelines from the Spring. And I think it's much better to have the samples as close as possible to related sdk.

**Comment by artursouza** [comment]
Your idea is fundamentally different from our vision for the SDK for the reasons below:

1. We minimize the dependency on Spring and Springboot and its footprint to keep the SDK as neutral as possible.

2. The samples are organized per SDK, fragmenting it further would make this SDK different. We need to review this proposal.

Long story short, to make these changes you will need to prepare a casa and review with the team. We had multiple sessions to review the proposals to reach the current form.

**Comment by JMayrbaeurl** [comment]
A lot of big enterprises are using Spring Boot for their Cloud native developments and I thought it's a great idea to provide really great support in Dapr for Spring Boot. Currently Dapr has no Spring Boot support. Just a sample showing how to use it in Spring Boot. The basic Spring support is minimal, too.

And Microsoft has recently invested a lot in supporting Spring and Spring Boot on Azure. So I was expecting the same kind of support from Dapr.

**Comment by JMayrbaeurl** [comment]
Moved my code in a new repo at https://github.com/JMayrbaeurl/dapr-spring-extensions
