### ISSUE TITLE
Update SDK for activate changes

### ISSUE THREAD

**Issue by LMWF** [dapr/java-sdk#284]
Changes are needed in the SDK corresponding to runtime changes here (see bottom of that issue for proposal): 
https://github.com/dapr/dapr/issues/1038

Reference for corresponding change in dapr/dotnet-sdk:
https://github.com/dapr/dotnet-sdk/pull/313

**Comment by AlexJuca** [comment]
@LMWF I am willing to work on this issue and submit a PR. Will have something soon.

**Comment by LMWF** [comment]
@AlexJuca Great!  I'll assign this to you.

/cc @artursouza

**Comment by AlexJuca** [comment]
@LMWF Awesome! Working on this.

**Comment by artursouza** [comment]
Hi, @AlexJuca. Thanks for working on this. Do you have an ETA for when you can get a PR out?

**Comment by artursouza** [comment]
@AlexJuca We have a PR fixing this issue. We accepted it due to the release we have scheduled for next week. You are free to enhance the solution and add a new PR.
