### ISSUE TITLE
Update Java SDK for latest proto for 0.8 and bidirectional binding

### ISSUE THREAD

**Issue by artursouza** [dapr/java-sdk#288]
## Expected Behavior

Java SDK should work with the master branch planned for release 0.8.

## Actual Behavior

Latest proto are not backwards compatible with this SDK.
Binding's API is not backwards compatible with this SDK.

## Steps to Reproduce the Problem

Try to use this SDK with the latest master from dapr-cli and dapr.

**Comment by youngbupark** [comment]
@artursouza @mukundansundar are you working on this?

**Comment by artursouza** [comment]
I am working on it today.

**Comment by artursouza** [comment]
Please, take a look at the PR above.
