### ISSUE TITLE
Support deserialization of generic types

### ISSUE THREAD

**Issue by xiazuojie** [dapr/java-sdk#293]
## Describe the proposal
The following [_deserialize_ API](https://github.com/dapr/java-sdk/blob/dbdab2ed696f62a906c307bd8e33e85084821824/sdk/src/main/java/io/dapr/serializer/DaprObjectSerializer.java#L33) asks for a `Class<T>`. It does not work with generic types.
```
<T> T deserialize(byte[] data, Class<T> clazz) throws IOException
```

Maybe add another method with the second param as `java.lang.reflect.Type`, which can accept both `java.lang.Class` and `java.lang.reflect.ParameterizedType`.
```
<T> T deserialize(byte[] data, java.lang.reflect.Type type) throws IOException
```

Jackson works with `java.lang.reflect.Type` as follows:
```
    public <T> T deserialize(byte[] data, java.lang.reflect.Type type) throws IOException {
        return objectMapper.readValue(data, objectMapper.constructType(type));
    }
```

**Comment by artursouza** [comment]
I agree with this change 100%. Can you make a PR?

**Comment by xiazuojie** [comment]
> I agree with this change 100%. Can you make a PR?

However, `java.lang.reflect.Type` is not easy for users to create an instance of. Jackson has a `TypeReference` to help users specify generic types more easily. Maybe we should work on something like that. 

It involves quite a bit of work. I can PR if it agrees with you.

**Comment by artursouza** [comment]
Makes sense. Please, go ahead.

**Comment by artursouza** [comment]
@xiazuojie Do you have plans to create a PR for this?

**Comment by artursouza** [comment]
I have created a PR. @xiazuojie please, take a look.

**Comment by xiazuojie** [comment]
It's exactly what I want. However, maybe we should also keep 
``<T> T deserialize(byte[] data, Class<T> clazz)``
so it's not a breaking change. Also for non-generic values, It's easier to use.

Sorry that I did not take time on the PR.

**Comment by xiazuojie** [comment]
Also, `TypeRef<T>` should implement `Comparable<TypeRef<T>>` (just as Jackson did) as suggested by [here](https://gafter.blogspot.com/2006/12/super-type-tokens.html).

**Comment by artursouza** [comment]
The serializer interface does not need two methods. It will just be confusing to users to implement two deserializers. On the other hand, every other public method in our APIs does have both variants - and that is more important for easy to use and backwards compatibility.

I will add the trick with Comparable so the type is enforced.

— Artur Souza
________________________________

**Comment by artursouza** [comment]
I've tried the Comparable<TypeRef<T>> trick. It does not block `new TypeRef(){}` from compiling. So, I did not add it. Actually, even `new TypeReference(){};` from Jackson also compiles. This trick does not seem to be applicable anymore.
