### ISSUE TITLE
[java-sdk] New jar to allow Dapr's callback API in SpringBoot

### ISSUE THREAD

**Issue by artursouza** [dapr/java-sdk#30]
A SpringBoot Application can easily depend on this jar and have Dapr's callback API running with a simple configuration change and implementing a base class/interface.

As an alternative to a base class, annotations can also be used, similar to how the .Net SDK does with ASP.Net.

**Comment by artursouza** [comment]
@ji11er

**Comment by ji11er** [comment]
Hi Artur,
I assume I follow the spec written here:
https://github.com/dapr/docs/tree/master/reference/api

right?,

Thanks
