### ISSUE TITLE
[java-sdk E2E] Actor activation/deactivation test

### ISSUE THREAD

**Issue by artursouza** [dapr/java-sdk#33]
Implement tests for java-sdk following same requirements as dapr/dapr#820:

Dapr config should be changed to support configuration and allow short time out (5s).
Implement a fake application listening to dapr.
app should implement actor related controller methods.
app should implement an extra method to return a "log" of events.

Add logic to add log entries for this test.
After actor is activated, add record to log array.
After actor method is invoked, add record to log array.
After actor is deactivated, add record to log array.

In test code:
Use ActorProxyImpl to invoke a method in the actor.
Sleep 5 seconds.
Make an API call to retrieve the log entries.
Validate the log entries contain: activate, deactivate and method invocation.

**Comment by AndresRoblesMX** [comment]
Is something else neeed beyon this what was done in this PR? https://github.com/dapr/java-sdk/pull/144
