### ISSUE TITLE
[Unit Tests] java-sdk: Gate PRs to ensure no PR reduces test coverage

### ISSUE THREAD

**Issue by wcs1only** [dapr/java-sdk#364]
## In what area(s)?

/area test-and-release

## Describe the feature

Enable PR gating on unit test coverage to ensure we do not regress on test coverage. For now the agreed upon rule is that no PR should reduce the test coverage. We may expand these rules later.

Part of dapr/dapr#2226 
## Release Note

RELEASE NOTE: **ADD** Added codecov rules to ensure that no PR reduces unit test coverage.

**Comment by artursouza** [comment]
We have this already. Just try a PR that reduces code coverage - I had one blocked recently and had to add unit tests.

**Comment by wcs1only** [comment]
> We have this already. Just try a PR that reduces code coverage - I had one blocked recently and had to add unit tests.

Oh, excellent. I created one ticket for each SDK. I should have verified before creating it. Closing issue.
