### ISSUE TITLE
[java-sdk] Create example for Dapr PubSub

### ISSUE THREAD

**Issue by artursouza** [dapr/java-sdk#37]
One example app for Dapr PubSub using Http.
One example app for Dapr PubSub using Grpc.
Documentation as README.md

**Comment by artursouza** [comment]
Code should work for both GRPC and HTTP since there is a common layer.

**Comment by artursouza** [comment]
Start the documentation for examples.

**Comment by artursouza** [comment]
Documentation should follow style used in https://github.com/dapr/samples

**Comment by artursouza** [comment]
One app to publish events.
Another app to receive events.

**Comment by artursouza** [comment]
Use kafka.

**Comment by marcosreyes05** [comment]
I can take this one
