### ISSUE TITLE
no default constructor for io.dapr.client.domain.CloudEvent

### ISSUE THREAD

**Issue by beiwei30** [dapr/java-sdk#385]
## Expected Behavior

A default constructor of CloudEvent is helpful for unmarshalling the payload to the exact type automatically in a Spring MVC application, for example:

```java

@RestController
public class MqBindingController {

    @Autowired
    @Qualifier("jsonDaprClient")
    private DaprClient daprClient;

    @GetMapping("/dapr/subscribe")
    public Flux<Subscription> subscribe() {
        Subscription[] subscriptions = new Subscription[]{
                new Subscription("pubsub", "BEIWEI_TEST_TOPIC_A", "A"),
                new Subscription("pubsub", "BEIWEI_TEST_TOPIC_B", "B"),
        };
        return Flux.fromArray(subscriptions);
    }

    @PostMapping("/A")
    public ResponseEntity<HttpStatus> topicA(@RequestBody byte[] payload) {
        ...
    }

    @PostMapping("/B")
    public ResponseEntity<HttpStatus> topicB(@RequestBody CloudEvent payload) { // this doesn't work
        ... 
    }
   ...
}
```

Spring complains no default constructor is present for CloudEvent.

## Actual Behavior

```java
    @PostMapping("/B")
    public ResponseEntity<HttpStatus> topicB(@RequestBody CloudEvent payload) {

    }
```

I believe this applies to all classes under io.dapr.client.domain.

## Release Note

RELEASE NOTE: **REFACTORED** CloudEvent serialization, also adding default constructor.

**Comment by mukundansundar** [comment]
Hi @beiwei30 thanks for raising this issue. Will you be able to work on this?

**Comment by arghya88** [comment]
@mukundansundar I see all the fields are final and hence just adding a default constructor is not going to work. What do you suggest we should do?
