### ISSUE TITLE
Review and ensure metadata is correctly set and transport 

### ISSUE THREAD

**Issue by skyao** [dapr/java-sdk#396]
## Expected Behavior

metadata should be correctly set and passed to dapr.

## Actual Behavior

At first, in state save method, there is no metadata to set. 

See file `src/main/java/io/dapr/client/domain/State.java`

I will submit a PR for this and later check other processes.

RELEASE NOTE: **RESOLVED** validated handling of metadata and fixed when applicable.

**Comment by skyao** [comment]
@artursouza Another PR has raised to add metadata parameter in get bulk request which is missing in java sdk. Please help to review. And now I only update the grpc api, for HTTP API, should we also support metadata in get bulk request (and also there is a ongoing PR to add metadata in get/bulk get response).

**Comment by skyao** [comment]
@artursouza A new more PR for metadata just raised.

**Comment by artursouza** [comment]
@skyao Thanks a lot. I will review the PR. Please, keep feature parity for the GRPC and HTTP clients for Dapr.

**Comment by artursouza** [comment]
I am handling all the remaining metadata logic in the PR above.
