### ISSUE TITLE
Update tracing sample doc to not use exporter

### ISSUE THREAD

**Issue by tcnghia** [dapr/java-sdk#404]
## Expected Behavior

Tracing doc does not use a trace exporter component, since exporter components are deprecated (see dapr/dapr#2337)

## Actual Behavior

Still here: 
https://github.com/dapr/java-sdk/blob/v0.10.0/examples/src/main/java/io/dapr/examples/tracing/README.md

## Steps to Reproduce the Problem

See doc here https://github.com/dapr/java-sdk/blob/v0.10.0/examples/src/main/java/io/dapr/examples/tracing/README.md 

## Release Note

RELEASE NOTE: **UPDATE** Java SDK trace sample at https://github.com/dapr/java-sdk/blob/v0.10.0/examples/src/main/java/io/dapr/examples/tracing/README.md to not use exporter components.

Thanks @artursouza for calling this out.

**Comment by tcnghia** [comment]
So:
- https://github.com/dapr/java-sdk/blob/v0.10.0/examples/src/main/java/io/dapr/examples/tracing/README.md only uses the components and configurations created by our CLI.
- CLI is now doing the right thing https://github.com/dapr/cli/pull/542

As a result, this doc does not need to change

**Comment by artursouza** [comment]
Thanks. LGTM

— Artur Souza
________________________________
