### ISSUE TITLE
States without etag is handled differently in gRPC and HTTP APIs

### ISSUE THREAD

**Issue by artursouza** [dapr/java-sdk#405]
## Expected Behavior

Get a state without eTag in gRPC and HTTP, eTag attribute should be null.

## Actual Behavior

eTag is null in HTTP and empty string in gRPC.

## Steps to Reproduce the Problem

Get state that does not have eTag.
Try the same in getBulkState too.

## Release Note

RELEASE NOTE: **FIX** missing eTag response for state APIs.

**Comment by arghya88** [comment]
I was looking at this and it seems it's happening because auto generated `DaprProtos.GetStateResponse` has `etag_ = "";`

```
public static final class GetStateResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:dapr.proto.runtime.v1.GetStateResponse)
      GetStateResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use GetStateResponse.newBuilder() to construct.
    private GetStateResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private GetStateResponse() {
      data_ = com.google.protobuf.ByteString.EMPTY;
      etag_ = "";
    }
```

@artursouza what would be the way to fix this?

**Comment by artursouza** [comment]
This should be fixed in the runtime ideally. In my opinion, the fallback is for the SDK to convert empty string to null for GRPC and HTTP implementation to keep them consistent.
