### ISSUE TITLE
How to upgrade to v1.0.0-rc-2

### ISSUE THREAD

**Issue by artursouza** [dapr/java-sdk#415]
These are instructions on the breaking changes on SDK v1.0.0-rc-2.

## DaprException

Now, every method in the SDK throws `DaprException` when there is an error returned by Dapr sidecar, containing error code via the `getErrorCode()` method. `DaprException` may contain a child exception in the `cause` property. Other exceptions can still be thrown, like `IllegalArgumentException` or `IOException`.

Here is an example of catching an exception in synchronous code:

```java
      try {
        client.getState("Unknown state store", "myKey", String.class).block();
      } catch (DaprException exception) {
        System.out.println("Error code: " + exception.getErrorCode());
        System.out.println("Error message: " + exception.getMessage());

        exception.printStackTrace();
      }
```

## ActorProxy and ActorProxyBuilder

`ActorProxyBuilder` now implements `Closeable`. This is needed because actor APIs are now over GRPC. It means that there is an instance of GRPC's `ManagedChannel` class that needs to be closed internally by the Dapr SDK and `ActorProxyBuilder` is responsible for keeping that reference. For this reason, the instance of ActorProxyBuilder should remain referenced until all the `ActorProxy` instances it created have been used. Then, it must be closed via the `close()` method.

See this example of using `ActorProxyBuilder`, where try-with-resource is used to automatically close `ActorProxyBuilder`:

```java
    try (ActorProxyBuilder<DemoActor> builder = new ActorProxyBuilder(DemoActor.class)) {
      ActorId actorId = ActorId.createRandom();
      DemoActor actor = builder.build(actorId);
      actor.say(message);
    }
```

**Comment by frochi42** [comment]
Concerning that DaprException introduction: Please make this a bit clearer, as it cannot be correct in the way it is described above.
It is stated: "every method in the SDK throws DaprException" which is definitly not true. E.g. there are many simple methods (aka getter) that simply return a value, so they never throw an exception.
But also for more complicated methods this sentence is misleading. If you look e.g. at CloudEvent.deserialize(). It prototype says it returns an IOExeption, which is obviously try as it calls ObjectMapper.readTree(). From the statement "every method throws DaprException" I would have expected that the method catches the IOException and wrap it into an DaprException, but this is not true.

**Comment by artursouza** [comment]
@frochi42 Makes sense. Thanks for the feedback. We updated the description.

**Comment by artursouza** [comment]
Closing in favor of https://github.com/dapr/java-sdk/issues/493
