### ISSUE TITLE
Implement getBulkSecret API

### ISSUE THREAD

**Issue by mukundansundar** [dapr/java-sdk#421]
## Describe the proposal

Following the implementation in runtime, https://github.com/dapr/dapr/issues/2168, implement the getBulkSecret for both HTTP and gRPC.
Implement unit tests.
Implement integration tests for both HTTP and gRPC APIs.
Modify secrets example for this API and add javadoc for the API.

**Comment by mukundansundar** [comment]
Hi @arghya88, thanks for picking this up. Are you working on this?

**Comment by arghya88** [comment]
@mukundansundar yes started on it. Will have a PR soon.

**Comment by artursouza** [comment]
@arghya88 Any updates on this issue?

**Comment by artursouza** [comment]
I have a PR for this. See above.
