### ISSUE TITLE
HTTP input is not properly encoded.

### ISSUE THREAD

**Issue by artursouza** [dapr/java-sdk#427]
## Expected Behavior

If the value of a state store (for example) has a "/", then it does not affect the URL path and the Dapr API works as expected.

## Actual Behavior

Dapr returns `Method Not Allowed` error because "/" (and other special chars) affect the URL path.

## Steps to Reproduce the Problem

Try to save state where state store contains "/" in the middle of the name.

## Release Note

RELEASE NOTE: **FIXED** input encoding for HTTP calls.

**Comment by mukundansundar** [comment]
breaking change since constants are removed.

**Comment by artursouza** [comment]
This is not breaking change because those constants are public simply because they are used in other packages. In Java there is no way to mark that as internal.
