### ISSUE TITLE
Why not implement java-sdk-springboot as a spring boot starter?

### ISSUE THREAD

**Issue by darren-wang** [dapr/java-sdk#441]
## Describe the proposal
Hi, I'm a java learner of dapr, i wonder why not implement  dapr-sdk-springboot according to spring boot common starter rules, that would be nicer for spring boot users.

**Comment by artursouza** [comment]
@darren-wang Can you provide an example of how it would work for the end user? I am not a spring boot expert, so I am eager to learn how we can better integrate with it.

**Comment by darren-wang** [comment]
> 
> 
> @darren-wang Can you provide an example of how it would work for the end user? I am not a spring boot expert, so I am eager to learn how we can better integrate with it.

HI, please check PR:

https://cla.opensource.microsoft.com/dapr/java-sdk?pullRequest=457

**Comment by artursouza** [comment]
@darren-wang We are closing on the release, so I took the liberty to have a PR where we incorporate your solution into  the sdk-springboot package directly. It is OK for that package to be springboot specific - that is the intent. We might refactor spring only stuff out of it later. The priority now is on springboot apps. Please, take a look a the PR.

**Comment by darren-wang** [comment]
Closed by https://github.com/dapr/java-sdk/pull/457 and https://github.com/dapr/java-sdk/pull/459

**Comment by artursouza** [comment]
Reopening since PR is not merged yet.
