### ISSUE TITLE
Add auto validation for Actors Examples

### ISSUE THREAD

**Issue by mukundansundar** [dapr/java-sdk#468]
## Describe the proposal
Add auto validation for Actors Java Examples. Follow the guides/examples in https://github.com/dapr/mechanical-markdown for more information on the validator used.
Similar to the PR https://github.com/dapr/java-sdk/pull/464.
Add the test for the actors example. It might need some changes to make the output deterministic enough for it to be validated.

**Comment by mukundansundar** [comment]
Need out of order processing support from mm.py. Since there are 3 actors in the example that are there which are called from independent threads, there is no order guarantee on which actor is called first. Similarly for the reminders and timers, since there is more than one actor, any actors can be pinged first or reminded of a state first. 

Created an issue https://github.com/dapr/mechanical-markdown/issues/18 to add ability to mm.py for outoforder processing.

The other option here is to limit the example to a single actor and then use the current available validations in mm.py. 

@artursouza thoughts? Personally I do not like changing the example and limiting it to a single actor call.

**Comment by artursouza** [comment]
@mukundansundar I agree. We need out of order processing before we can add this validation.

**Comment by mukundansundar** [comment]
With the addition of [`match_order: none`](https://github.com/dapr/mechanical-markdown/blob/main/examples/io.md#match-order) and [`output_match_mode`](https://github.com/dapr/mechanical-markdown/blob/main/examples/io.md#match-mode) directives, we have the capabilities to match/validate non-deterministic output order  as well as substring matches for lines now.
