### ISSUE TITLE
Dapr-1.0.0-rc3 (and newer) breaks CloudEvent.deserialize for data-types other then String

### ISSUE THREAD

**Issue by frochi42** [dapr/java-sdk#477]
## In what area(s)?

/area runtime

## Ask your question here

when updating from dapr 0.10.0 to the release candidates (first introduced in 1.0.0-rc3) we first noticed that many of our unit test were failing. Having a deeper look shows that this is also a runtime problem: the CloudEvent.deserialize method does not work as before. It deserialized the payload as "LinkedHashMap".
The reason is obviously that the type for "data" was changed from String to Object. With that, the deserializer cannot write the json-string into the correct object class.
Up to rc3 there was the code-snippet
    if (node.has("data") && !node.get("data").isNull()) {
      JsonNode dataNode = node.get("data");
      if (dataNode.isTextual()) {
        data = dataNode.textValue();
      } else {
        data = node.get("data").toString();
      }
    }
Hence data contained a valid json-String after deserialisation. With that, we were able to invoke a second MAPPER.deserialize() on the data-field.
We were able to implement a workaround: We simply do not use dapr's CloudEvent class at all. Instead we provide an own version of this class (which is basically a copy of the previous version of dapr's CloudEvent class).
But is that the intended usage? I think dapr should provide a mean to correctly deserialize into the client's data-class

**Comment by artursouza** [comment]
I am looking into how to make this easier for apps to handle their own deserialization.

**Comment by frochi42** [comment]
@yaron2 : thanks for you suggestion. I just compared the rc-version sources in github: The breaking change in CloudEvent was introduced in rc-2. So falling back to rc-3 makes no sense.

**Comment by artursouza** [comment]
I have found a way to deserialize correctly from LinkedHashMap. Just use `ObjectMapper.convertValue()`. See in the test code below:

```java
public class CloudEventTest {

  private static final ObjectMapper OBJECT_MAPPER = new ObjectMapper();

  public static class MyClass {
    public int id;
    public String name;
  }

  @Test
  public void deserializeObjectClass() throws Exception {
    String content = "{\n" +
        "    \"specversion\" : \"1.0\",\n" +
        "    \"type\" : \"com.github.pull_request.opened\",\n" +
        "    \"source\" : \"https://github.com/cloudevents/spec/pull\",\n" +
        "    \"subject\" : \"123\",\n" +
        "    \"id\" : \"A234-1234-1234\",\n" +
        "    \"time\" : \"2018-04-05T17:31:00Z\",\n" +
        "    \"comexampleextension1\" : \"value\",\n" +
        "    \"comexampleothervalue\" : 5,\n" +
        "    \"datacontenttype\" : \"application/json\",\n" +
        "    \"data\" : {\"id\": 1, \"name\": \"hello world\"}\n" +
        "}";

    MyClass expected = new MyClass() {{
      this.id = 1;
      this.name = "hello world";
    }};

    CloudEvent cloudEvent = CloudEvent.deserialize(content.getBytes());
    assertEquals("application/json", cloudEvent.getDatacontenttype());

    MyClass myObject = OBJECT_MAPPER.convertValue(cloudEvent.getData(), MyClass.class);
    assertEquals(expected.name, myObject.name);
  }
}
```

**Comment by artursouza** [comment]
Closing this issue. See solution above.

**Comment by frochi42** [comment]
Hi @artursouza ,
sorry for reacting so late. We were very busy changing the dapr-runtime ...
I can confirm that the the suggested ObjectMapper.convertValue() solution works (at least for the examples I tested so far).
Nevertheless we don't think it is a good solution. As you know, convertValue would first serialize the data, before calling readValue again. Overall it is just superfluous work. First you deserialize in CloudEvent deserialize, then you serialize again, before finally deserialize.
What we would prefer is an additional CloudEvent.deserialize method which lets users specify the desired target-class of the data. Don't know whether that is feasable.
Additionally, it turned out that it makes sense to have the used ObjectMapper configurable. E.g. we typically need to set
           .findAndRegisterModules()
            .registerModule(new ParameterNamesModule())
            .registerModule(new Jdk8Module())
            .registerModule(new JavaTimeModule())
            .disable(DeserializationFeature.ADJUST_DATES_TO_CONTEXT_TIME_ZONE)
            .configure(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES, false)
            .setSerializationInclusion(JsonInclude.Include.NON_NULL);
on it. That means, CloudEvent.deserialize() would also (optionally) need a parameter to pass the ObjectMapper.

As I already said: We currently implemented a private version of the CloudEvent class which works. However, it would be nice to make use of CloudEvent directly in order to be future-proof to changes in this area.
