### ISSUE TITLE
Remove Context from API

### ISSUE THREAD

**Issue by artursouza** [dapr/java-sdk#478]
## Expected Behavior

Context should be handled separately from domain objects. As per discussion in #453 

## Actual Behavior

Context is a property of request classes.

## Steps to Reproduce the Problem

See the Request classes.

## Release Note

RELEASE NOTE:  **REMOVED** Context from request and response objects.

**Comment by artursouza** [comment]
@xiazuojie Please, comment on this issue so I can assign it to you.

**Comment by xiazuojie** [comment]
I agree
