### ISSUE TITLE
allow supplied ObjectMapper to DefaultObjectSerializer

### ISSUE THREAD

**Issue by xiazuojie** [dapr/java-sdk#496]
## Describe the proposal
At the moment, there is no way to customise JSON serialization behaviour if using DefaultObjectSerializer.
I suggest allowing supplied ObjectMapper to DefaultObjectSerializer.

**Comment by artursouza** [comment]
Applications should not use DefaultObjectSerializer beyond test and samples. Applications are expected to implement their own serializer class. That way, they can have any customization needed, including using a non-JSON serialization.
