### ISSUE TITLE
protoc-jar-maven-plugin is a dependency for dapr-sdk-autogen

### ISSUE THREAD

**Issue by xiazuojie** [dapr/java-sdk#501]
## Expected Behavior
protoc-jar-maven-plugin is only used to build module dapr-sdk-autogen. It's not a dependency.

## Actual Behavior
protoc-jar-maven-plugin is in dependency list of dapr-sdk-autogen.

## Release Note

RELEASE NOTE:

**Comment by artursouza** [comment]
Please, send the PR fixing this.
