### ISSUE TITLE
please support JDK1.8 env with test code

### ISSUE THREAD

**Issue by pli2014** [dapr/java-sdk#512]
## Describe the proposal

looked at this file: sdk-tests/pom.xml 
<maven.compiler.source>8</maven.compiler.source>
<maven.compiler.target>8</maven.compiler.target>

plugins 👍  
released with 8 for support minimal version.
<plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-compiler-plugin</artifactId>
        <version>3.8.1</version>
        <configuration>
          <release>8</release>
        </configuration>
      </plugin>

**Comment by artursouza** [comment]
@pli2014 We generate our assets (jars) with JDK 8 support so legacy Java apps can use the Dapr's Java SDK. Could you clarify what is the advantage to downgrade to Java 8 in the integration test project since that project is not consumed by apps?

**Comment by artursouza** [comment]
Closing issue.
