### ISSUE TITLE
Potential issue in io.dapr.client.DaprClientHttp#executeStateTransaction

### ISSUE THREAD

**Issue by beiwei30** [dapr/java-sdk#514]
In io.dapr.client.DaprClientHttp#executeStateTransaction, there's one line of code like below:

https://github.com/dapr/java-sdk/blob/9c5084b56fdfc9ab16111589c69248cb9cc211e2/sdk/src/main/java/io/dapr/client/DaprClientHttp.java#L398

Instead, I believe the right logic should be:

```go
        // Custom serializer, so everything is byte[].
        internalOperationObjects.add(new TransactionalStateOperation<>(operation.getOperation(),
            new State<>(state.getKey(), data, state.getEtag(), state.getMetadata(), state.getOptions())));
```

**Comment by artursouza** [comment]
@beiwei30 Yes, this is a bug. We need to fix this ASAP. I was planning on releasing 1.0.1 today but I will work on this instead and add it to the hotfix release. We also need IT to make sure this bug does not come back. nice catch!

**Comment by artursouza** [comment]
This issue is not present in the gRPC client, which is what is used by default in the SDK. So, it is not as urgent. Still, I am working on the fix.
