### ISSUE TITLE
How to use gRPC service invocations?

### ISSUE THREAD

**Issue by mthmulders** [dapr/java-sdk#535]
After following the [Invoking a Grpc endpoint](https://github.com/dapr/java-sdk/tree/master/examples/src/main/java/io/dapr/examples/invoke/grpc) example, I wanted to give it a try.

So I have created two applications, a server and a client, both using Spring Boot. They share a common submodule that holds the Protobuf definitions, and that generates the corresponding Java classes.

## Client

The server has this in its Spring Boot **application.yml**:

```yml
grpc:
  port: 5005
```

I start the sidecar for that application with `dapr run --app-id user-service -P grpc -p 5005`, and then run the app from my IDE. The sidecar logs (among other things)

```
INFO[0026] application discovered on port 5005           app_id=user-service instance=edsger scope=dapr.runtime type=log ver=1.1.2
INFO[0026] actor runtime started. actor idle timeout: 1h0m0s. actor scan interval: 30s  app_id=user-service instance=edsger scope=dapr.runtime.actor type=log ver=1.1.2
INFO[0026] placement tables updated, version: 0          app_id=user-service instance=edsger scope=dapr.runtime.actor.internal.placement type=log ver=1.1.2
ERRO[0026] error getting topic list from app: rpc error: code = Unimplemented desc = Method not found: dapr.proto.runtime.v1.AppCallback/ListTopicSubscriptions  app_id=user-service instance=edsger scope=dapr.runtime type=log ver=1.1.2
INFO[0026] dapr initialized. Status: Running. Init Elapsed 26598.345999999998ms  app_id=user-service instance=edsger scope=dapr.runtime type=log ver=1.1.2
```

But I'm not sure if that's relevant.

## Server

The client has a Spring bean for the `DaprClient` defined:
```java
@Bean
public DaprClient daprClient() {
    return new DaprClientBuilder().build();
}
```

And it uses that bean like so:

```java
return daprClient.invokeMethod(APP_ID, "register", user, HttpExtension.NONE, RegisterResponse.class)
            .blockOptional()
            .map(response -> response.userId)
            .map(UUID::fromString)
            .orElse(null);
```

I start the sidecar for the client with `dapr run --app-id client`, and then start the client itself from my IDE.

When I invoke an endpoint on the client (which will eventually be done by a JavaScript frontend app, so it's not going through Dapr here), I'm getting an exception in the logs:

```
java.net.ConnectException: Connection refused
	at java.base/sun.nio.ch.Net.pollConnect(Native Method)
	at java.base/sun.nio.ch.Net.pollConnectNow(Net.java:660)
	at java.base/sun.nio.ch.NioSocketImpl.timedFinishConnect(NioSocketImpl.java:549)
	at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:597)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:333)
	at java.base/java.net.Socket.connect(Socket.java:648)
	at okhttp3.internal.platform.Platform.connectSocket(Platform.kt:120)
	at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.kt:295)
	at okhttp3.internal.connection.RealConnection.connect(RealConnection.kt:207)
	at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:226)
	at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:106)
	at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:74)
	at okhttp3.internal.connection.RealCall.initExchange$okhttp(RealCall.kt:255)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:32)
```

From inspecting the request using the debugger, it appears to me that the client tries to connect to localhost:3500 - but I don't know why. Also, all the relevant breakpoints where located in classes with *Http* in their name. The `DaprClientBuilder` even has a comment saying:

```java
/**
 * A builder for the DaprClient,
 * Currently only and HTTP Client will be supported.
 */
```

I'm not sure how to interpret this. Should I be able to do gRPC-based service invocations from Java to Java? If so, how? How can I verify it is indeed using gRPC and not HTTP? How can I troubleshoot these connection issues?

Thanks in advance for any pointers you may have!

**Comment by artursouza** [comment]
@mthmulders Thanks for creating an issue for this. There are a few things to clarify here.

First, Dapr invokes gRPC servers but only for the `dapr.proto.runtime.v1.AppCallback` API. Dapr does not understand the proto that is generated for the application. This is a limitation for Dapr invoking gRPC endpoints.

Second, Dapr works based on sidecar. Port 3500 is the default port for Dapr sidecar, so a sidecar must be running for this connection to succeed. If more than one sidecar is running, then the port must change - running the app via the `dapr` CLI takes care of that automatically.

Third, SDKs in this version of Dapr, only use HTTP when invoking another service (HTTP or gRPC endpoint) - this is the protocol used between client app and the Dapr sidecar - while the protocol for your service app remains gRPC. Dapr sidecar knows how to handle the translation between protocols here.

Last but not least, please look at this example: https://github.com/dapr/java-sdk/tree/master/examples/src/main/java/io/dapr/examples/invoke/grpc

I hope it helps you with this problem.

**Comment by mthmulders** [comment]
Thanks for the reply, @artursouza. Just to make sure I understand you correctly, let me go through it one by one...

> First, Dapr invokes gRPC servers but only for the `dapr.proto.runtime.v1.AppCallback` API. Dapr does not understand the proto that is generated for the application. This is a limitation for Dapr invoking gRPC endpoints.

Do I understand correctly that Dapr *only* uses gRPC for getting information from the application it accompanies, such as "which services do you expose"? But *not* for actually invoking those business services - invoking the business services that my application exposes only works over HTTP?
 
> Second, Dapr works based on sidecar. Port 3500 is the default port for Dapr sidecar, so a sidecar must be running for this connection to succeed. If more than one sidecar is running, then the port must change - running the app via the `dapr` CLI takes care of that automatically.

Got it: I've updated the command to run the sidecar to `dapr run --app-id user-service -P grpc -p 5005 -H 3500`. The sidecar logs:

```
INFO[0000] application protocol: grpc. waiting on port 5005.  This will block until the app is listening on that port.  app_id=user-service instance=edsger scope=dapr.runtime type=log ver=1.1.2
INFO[0000] application discovered on port 5005           app_id=user-service instance=edsger scope=dapr.runtime type=log ver=1.1.2
```

Which looks good to me! But running the client again now gives a different stacktrace:

```
io.dapr.exceptions.DaprException: UNIMPLEMENTED: Method not found: dapr.proto.runtime.v1.AppCallback/OnInvoke
	at io.dapr.client.DaprHttp$ResponseFutureCallback.onResponse(DaprHttp.java:350)
	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)
	Suppressed: java.lang.Exception: #block terminated with an error
		at reactor.core.publisher.BlockingOptionalMonoSubscriber.blockingGet(BlockingOptionalMonoSubscriber.java:139)
		at reactor.core.publisher.Mono.blockOptional(Mono.java:1748)
  at <redacted>.UserService.createUser(UserService.java:23)
```

In [another part of the Dapr documentation](https://docs.dapr.io/developing-applications/building-blocks/service-invocation/howto-invoke-discover-services/), I found an alternative approach to invoking the service. Unfortunately, it fails with a similar message:

```sh
$ curl http://localhost:3500/v1.0/invoke/user-service/method/register -X POST -v
[... skipped ...]
< HTTP/1.1 501 Not Implemented
< Server: fasthttp
<
{"code":12,"message":"Method not found: dapr.proto.runtime.v1.AppCallback/OnInvoke"}
```

> Third, SDKs in this version of Dapr, only use HTTP when invoking another service (HTTP or gRPC endpoint) - this is the protocol used between client app and the Dapr sidecar - while the protocol for your service app remains gRPC. Dapr sidecar knows how to handle the translation between protocols here.

So the client app speaks HTTP to the sidecar, which then communicates with the other sidecar, which then speaks gRPC to the service app? That would contradict my understanding of the first part of your response. 

> Last but not least, please look at this example: https://github.com/dapr/java-sdk/tree/master/examples/src/main/java/io/dapr/examples/invoke/grpc

I started by studying that example (as my OP also mentioned)... :-)

Looking forward to your response!

**Comment by mthmulders** [comment]
I didn't mention before, and I think it's part of the puzzle... I'm also using the [gRPC Spring Boot starter](https://github.com/LogNet/grpc-spring-boot-starter). That doesn't expose the `dapr.proto.runtime.v1.AppCallback` by default, but I managed to do so.

Now I don't see `{"code":12,"message":"Method not found: dapr.proto.runtime.v1.AppCallback/OnInvoke"}` anymore, but rather `{"code":12,"message":"Method dapr.proto.runtime.v1.AppCallback/OnInvoke is unimplemented"}`.

I'll see if I can get the two to cooperate...

**Comment by artursouza** [comment]
Hi @mthmulders. Thanks for looking into the example and sorry if I missed that in your original issue.

I am not familiar with gRPC Spring Boot starter, so I cannot help much there.

Regarding your other question about the communication between apps and sidecars, here is a quick diagram:
app A ----- grpc or http -------> sidecar A -------- grpc -----------> sidecar B ----- grpc or http ----> app B
When you use the Java SDK to invoke a grpc endpoint, the call is like:
app A ---- http -------> sidecar A ---- grpc ------> sidecar B --------- grpc -----> app B


Regarding the question about http vs grpc endpoint in your app, Dapr can invoke any of your existing HTTP endpoints directly. For gRPC, dapr does not understand your service API, it only understand the Dapr defined AppCallback service, so your app must implement that if you want Dapr sidecar to talk to it over gRPC. This is a limitation that we could not find a solution yet.

**Comment by mthmulders** [comment]
Hi @artursouza, thanks a lot for the explanation. I think I'm having a 💡 moment... Please allow me to verify if I understand correctly:

Dapr always uses gRPC for communication between sidecars. If you're using the Java SDK for Dapr,
* on the client-side, it doesn't support gRPC, it only supports HTTP. A Java application can only communicate with its sidecar using HTTP.
* on the server-side,
  * you _could_ use gRPC, but you *must* implement the *AppCallback* service, and more specifically, the *OnInvoke* method. It is basically the protocol between the Dapr sidecar and the application that it accompanies. If the (Java) application happens to expose gRPC endpoints, Dapr doesn't understand/recognise them.
  * if the (Java) application exposes HTTP endpoints, Dapr does understand them; it seems the convention is to expose an endpoint `POST /<name-of-method>`.

Does that make sense from your point of view?

**Comment by artursouza** [comment]
@mthmulders Your understanding is correct as of now.

**Comment by artursouza** [comment]
I am closing this issue. Please, reopen if you still have further questions on this topic.

**Comment by mthmulders** [comment]
Thanks for confirming, and an additional thank you for helping me out in understanding this!

**Comment by nobodyiam** [comment]
> on the client-side, it doesn't support gRPC, it only supports HTTP. A Java application can only communicate with its sidecar using HTTP.

This is not correct, as long as the system property `dapr.api.methodInvocation.protocol` or environment variable `DAPR_API_METHOD_INVOCATION_PROTOCOL` is set to `GRPC`, then the invocation between java client and dapr sidecar will use grpc.

https://github.com/dapr/java-sdk/blob/dfd0d5c7af167072434d680859e851c9adfc94bd/sdk/src/main/java/io/dapr/client/DaprClientBuilder.java#L120-L130

**Comment by artursouza** [comment]
> > on the client-side, it doesn't support gRPC, it only supports HTTP. A Java application can only communicate with its sidecar using HTTP.
> 
> This is not correct, as long as the system property `dapr.api.methodInvocation.protocol` or environment variable `DAPR_API_METHOD_INVOCATION_PROTOCOL` is set to `GRPC`, then the invocation between java client and dapr sidecar will use grpc.
> 
> https://github.com/dapr/java-sdk/blob/dfd0d5c7af167072434d680859e851c9adfc94bd/sdk/src/main/java/io/dapr/client/DaprClientBuilder.java#L120-L130

@nobodyiam Yes, that is correct. It is possible to use service invocation for gRPC but it is not recommended. The default is HTTP. On the other hand, for the other APIs, the default protocol is gRPC for app to sidecar communication.

**Comment by nobodyiam** [comment]
> Yes, that is correct. It is possible to use service invocation for gRPC but it is not recommended. 

@artursouza Regarding this statement, may I ask why invocation with gRPC is not recommended?

**Comment by hspaay** [comment]
@artursouza This seems to contradict with issue https://github.com/dapr/dapr/issues/2342.
Can you please confirm if pt 4:
> [cross-protocol] Caller ---HTTP--> Dapr Sidecar --Internal gRPC--> Dapr Sidecar --gRPC--> Callee

... requires that the gRPC server implements an 'invokeMethod' method?
Scouring through the docs this aspect isn't explained and the reader is left wondering what can and cannot be done with cross protocol invocation.
