### ISSUE TITLE
External repositories not needed anymore in README

### ISSUE THREAD

**Issue by delvh** [dapr/java-sdk#550]
Currently, the following code can be found inside the README:
```xml
  <repositories>
    ...
    <!-- BEGIN: Dapr's repositories -->
    <repository>
      <id>oss-snapshots</id>
      <url>https://oss.sonatype.org/content/repositories/snapshots</url>
    </repository>
    <repository>
      <id>oss-release</id>
      <url>https://oss.sonatype.org/content/repositories/releases/</url>
    </repository>
    <!-- END: Dapr's repositories -->
    ...
  </repositories>
```
As far as I can see and have tested, these repositories are no longer needed to download the SDK using Maven, as Dapr has now been uploaded to Maven Central.
I'd suggest removing this entry then from the README.

**Comment by artursouza** [comment]
@delvh Please, create a PR.

**Comment by delvh** [comment]
I have seen that the same might apply to Gradle:
```gradle
    ...
    // Dapr repositories
    maven {
      url "https://oss.sonatype.org/content/repositories/snapshots"
	  mavenContent {
	    snapshotsOnly()
	  }
    }
    maven {
	  url "https://oss.sonatype.org/content/repositories/releases/"
    }
```
Can someone test whether its unnecessary there too, please?
I am not too familiar with gradle. I'd assume it to be true there too, but I don't know for sure whether it is.
Because if that is the case, I'd remove both at once.
