### ISSUE TITLE
Unable to build the dapr-sdk-autogen

### ISSUE THREAD

**Issue by naichowdhury** [dapr/java-sdk#561]
## Expected Behavior

run mvn clean package successfully in dapr-sdk-autogen

## Actual Behavior

A fatal error occurred when run mvn clean package

## Steps to Reproduce the Problem

Environment

- Dapr version: 1.1.0 (1.2.0-SNAPSHOT is not available in maven repo)
- Dapr branch: master
- OS name: windows 10
- OS version: 10.16
- OS arch: x86_64
- JDK version: 1.8.0_281
- JDK vendor: Oracle Corporation
- Maven version: 3.6.3

How to reproduce this problem

- set up the environmen according to the above information
- run mvn clean package

Detailed Information

[issue_dapr_sdk_autogen.txt](https://github.com/dapr/java-sdk/files/6589224/issue_dapr_sdk_autogen.txt)

## Release Note

RELEASE NOTE:

**Comment by rovangju** [comment]
This could be a dupe of #555?

**Comment by naichowdhury** [comment]
> This could be a dupe of #555?

checked the issue #555 but that one looks different. Am facing issue related to error in SSL handshaking with no idea where to get the certificate from and add into cacerts as no url is defined. the verbose output of the error is attached in the original issue

**Comment by dasamitk** [comment]
1. Build the project in debug mode (mvn clean install -X), it will give you the URI with certificate issue: https://raw.githubusercontent.com/dapr/dapr/v1.2.0-rc.3/dapr/proto/common/v1/common.proto 
2. Export the SSL certificate using Firefox. You can export it by hitting the URL in the browser and then select the option to export the certificate. Let's assume the cert file name is dapr.cer
3. Go to your JRE_HOME/bin or JDK/JRE/bin Execute Command: keytool -keystore ..\lib\security\cacerts -import -alias dapr -file path_to_certificate_file.cer

This resolved for me.

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for dapr-sdk-parent 1.2.0-SNAPSHOT:
[INFO]
[INFO] dapr-sdk-parent .................................... SUCCESS [ 11.685 s]
[INFO] dapr-sdk-autogen ................................... SUCCESS [01:46 min]
[INFO] dapr-sdk ........................................... SUCCESS [01:02 min]
[INFO] dapr-sdk-actors .................................... SUCCESS [ 41.333 s]
[INFO] dapr-sdk-springboot ................................ SUCCESS [ 14.473 s]
[INFO] dapr-sdk-examples .................................. SUCCESS [01:02 min]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  05:00 min
[INFO] Finished at: 2021-06-07T18:02:44+05:30
[INFO] ------------------------------------------------------------------------

**Comment by naichowdhury** [comment]
thanks, it worked, closing the issue
