### ISSUE TITLE
Which way to use DaprClient is recommended?

### ISSUE THREAD

**Issue by darren-wang** [dapr/java-sdk#563]
Hi, there are 2 ways to use `DaprClient` in current demos.

first one is to create a new `DaprClient` instance whenever you need to talk to dapr runtime:

```java
try (DaprClient client = (new DaprClientBuilder()).build()) {
 // ...
}
```

second one is to create a `DaprClient` bean before usage, then inject it into code:

```java
@Autowired
private DaprClient client;
```

since our project is Spring-based, the second way seems attractive, however, is it thread-safe to use `DaprClient` in the second way, since Spring' bean is singleton by default.

**Comment by artursouza** [comment]
The second way is preferred because you reuse the client. The client is thread-safe and designed to be reused.

**Comment by darren-wang** [comment]
Got it, hope all the demos can be updated with the recommended way.

**Comment by artursouza** [comment]
> Got it, hope all the demos can be updated with the recommended way.

Not every demo uses Spring. Still, the client can be reused. Feel free to send PRs fixing those. Maybe one at a time, so we can agree on a strategy.

**Comment by delvh** [comment]
> The second way is preferred because you reuse the client. The client is thread-safe and designed to be reused.

But what about the choice of letting it implement `AutoCloseable`?
Are there any resources that might not be freed by taking this approach, even after the JVM shut down (i.e. used ports)?

**Comment by darren-wang** [comment]
> ources that might not be freed by taking this approach, even after the JVM shut down (i.e. used ports)?

that's what confusing me too. i guess the only way to find it out is to read the source codes.
