### ISSUE TITLE
Java SDK 1.1.0 imports unexist pkg

### ISSUE THREAD

**Issue by LaurenceLiZhixin** [dapr/java-sdk#588]
## Actual Behavior

import io.dapr.v1.DaprGrpc;
can't find package
![图片](https://user-images.githubusercontent.com/45508533/127294071-b2416a71-c763-4608-ae7b-2dc057697244.png)

## Release Note

RELEASE NOTE:

**Comment by artursouza** [comment]
This is auto-generated by the sdk-autogen package. Please, build locally with `mvn install` first.

**Comment by LaurenceLiZhixin** [comment]
The problem is that I use M1 chip arm64 arch and can't use mvn plugin to compile proto.

**Comment by javahwh** [comment]
I also encountered this problem. How to solve it?

**Comment by mthmulders** [comment]
Have you tried building from a [Rosetta-enabled terminal](https://www.courier.com/blog/tips-and-tricks-to-setup-your-apple-m1-for-development/)? I would guess that the osx-x86_64 gRPC compiler should work, there.
