### ISSUE TITLE
Latest dependency version in Maven Central is 1.2.0-rc1

### ISSUE THREAD

**Issue by rovangju** [dapr/java-sdk#592]
## Expected Behavior

See the latest and greatest in maven central, including officially cut 1.2.0 release

## Actual Behavior

Only see the 1.2.0-rc1 version of the Dapr Java SDK dependencies as the 'latest' 

## Steps to Reproduce the Problem

Take a lookskie: https://search.maven.org/artifact/io.dapr/dapr-sdk-springboot

**Comment by artursouza** [comment]
Thanks for the reminder. We found that the build has a flaky test and did not get published. It is fixed now.
