### ISSUE TITLE
[Integration test] Can not run in IDEA

### ISSUE THREAD

**Issue by znzn007007** [dapr/java-sdk#593]
# Describe Question
When I run `io.dapr.it.methodinvoke.http.MethodInvokeIT`.
It shows
![image](https://user-images.githubusercontent.com/46895412/129294833-93798f07-7bff-42ff-8163-3500102b8918.png)

# Environment
JAVA:11.0.11.hs-adpt
OS:Ubuntu 20.04.2 LTS
MAVEN:3.8.3(using sdkman)

**Comment by TomCools** [comment]
Your output states:

`exec: "mvn": executable file not found in $PATH`

You most likely still need to add Maven to your path manually. 
I would expect sdkman to have done that for you (at least, if you have execute the 'sdk default maven 3.8.3' command), but that's where I'd check first.

**Comment by znzn007007** [comment]
> Your output states:
> 
> `exec: "mvn": executable file not found in $PATH`
> 
> You most likely still need to add Maven to your path manually.
> I would expect sdkman to have done that for you (at least, if you have execute the 'sdk default maven 3.8.3' command), but that's where I'd check first.

It can work properly when I select this, thanks for helping 
![image](https://user-images.githubusercontent.com/46895412/130030314-309e0f34-cd5e-46f3-bf1c-3d4164684999.png)
