### ISSUE TITLE
Remove dependency on jcenter

### ISSUE THREAD

**Issue by artursouza** [dapr/java-sdk#608]
## Expected Behavior

JCenter is being shut down, so we should depend on another public mirror: https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

## Actual Behavior

SDk build depends on a public mirror reaching end of life.

## Steps to Reproduce the Problem

See notice: https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

## Release Note

RELEASE NOTE: **MIGRATED** out of JCenter as a Maven repository.

**Comment by mthmulders** [comment]
What exactly do we use JCenter for? I believe all released versions of the Dapr SDK for Java are already published to Maven Central...

**Comment by artursouza** [comment]
It is where we are downloading our dependencies from.
