### ISSUE TITLE
Proposal

### ISSUE THREAD

**Issue by drishtirai** [dapr/java-sdk#621]
## Describe the proposal
It would be fantastic if the Dapr Java SDK came with pre-configured or easily customizable mock implementations for commonly used things like DaprClient and ActorClient to make unit and integration testing easier.

It would also be wonderful if the protocol HTTP/gaps could be set during testing for ActorClient so that an in-memory fake HTTP web server could be used instead of gRPC.

**Comment by artursouza** [comment]
Spam.
