### ISSUE TITLE
Proposal

### ISSUE THREAD

**Issue by drishtirai** [dapr/java-sdk#622]
## Describe the proposal
If you're using Kubernetes, you may add Dapr to your cluster to get the most out of it: https://docs.dapr.io/operations/hosting/kubernetes/kubernetes-overview/

The helm chart is what I use.

If you wish to use dapr in your Docker image for any reason, you must first download and install it in your runtime environment (e.g.: run wget or curl, and extract it)

**Comment by artursouza** [comment]
spam.
