### ISSUE TITLE
When I use sdk to publish and subscribe, my subscription is not available, and no error is reported. What problems can cause this phenomenon

### ISSUE THREAD

**Issue by tiankanghello** [dapr/java-sdk#630]
my code is
@RestController
public class MessageSubscriberController {
    /**
     * Handles a registered publish endpoint on this app.
     * @return A message containing the time.
     */
    @Topic(name = "app_create", pubsubName = "pubsub")
    @PostMapping(path = "/app_create")
    public Mono<Void> handleMessage(@RequestBody(required = false) byte[] body) {
        return Mono.fromRunnable(() -> {
            try {
                System.out.println("Subscriber got: " + new String(body));
            } catch (Exception e) {
                throw new RuntimeException(e);
            }
        });
    }
}
and redis data is:
{"data":"{\"topic\":\"app_create\",\"data\":\"{\\\"name\\\":\\\"spa\\\",\\\"id\\\":\\\"I7x68nf3E4B4d2x95aq8spIa31sztcs7\\\",\\\"tenant\\\":\\\"http://demo.cipherchina.com:8444\\\"}\",\"id\":\"f2986fbe-8cbd-4ac4-b04b-95f3e9f70bcc\",\"specversion\":\"1.0\",\"source\":\"app\",\"traceid\":\"00-0de2b2b1589b711e465ed07b796419a9-0983524c9a443b89-01\",\"expiration\":\"2021-09-10T07:13:13Z\",\"datacontenttype\":\"application/json\",\"type\":\"com.dapr.event.sent\",\"pubsubname\":\"pubsub\"}"}

my subscription cannot be accepted  What caused this

**Comment by artursouza** [comment]
Do you have Spring configured correctly for your app? Is it listening to a port?
