### ISSUE TITLE
Change DaprClient generic classes with correct Dapr API structures

### ISSUE THREAD

**Issue by yaron2** [dapr/java-sdk#64]
The current [DaprClient](https://github.com/dapr/java-sdk/blob/java_sdk_wip/sdk/src/main/java/io/dapr/client/DaprClient.java) doesn't expose or conform to the Dapr API.

The generic classes that are currently used require the user to hand-craft the payload sent to Dapr.
An SDK should encapsulate the Dapr API surface into strongly-typed classes for ease of use and understanding.

A partial list of the features that need to be exposed by the DaprClient:

1. State consistency
2. State concurrency
3. State metadata
4. Pub/Sub metadata
5. Service invocation metadata
6. Bindings metadata

This can be remedied by including custom classes instead of generic classes, similar to the gRPC auto-generated classes (envelopes).

**Comment by artursouza** [comment]
Thanks, we found this out recently. We will keep this issue open as a quality check for our project closure.

**Comment by artursouza** [comment]
Current state of the DaprClient interface in Java SDK's master branch:
- GetState: consistency, concurrency, retry and etag. Complete.
- DeleteState: consistency, concurrency, retry and etag. Complete.
- SaveState: consistency, concurrency, retry and etag. Complete.
- OutputBinding: data is present but metadata is missing. Not complete.
- Invoke Service: data and metadata are present. Complete.
- Publish PubSub: data and metadata are present. Complete.


Summary:
Only action item pending is to support metadata for output bindings.
