### ISSUE TITLE
Java cannot specify httpEndpoint. It is recommended to increase. 

### ISSUE THREAD

**Issue by owenwong520** [dapr/java-sdk#646]
## Describe the proposal
Dotnet sdk class DaprClientBuider have UserHttpEndpoint method. Specify http terminal.

There is no similar method for java sdk. This method can facilitate business debugging.

Dotnet code：

```
/// <summary>
/// Overrides the HTTP endpoint used by <see cref="DaprClient" /> for communicating with the Dapr runtime.
/// </summary>
/// <param name="httpEndpoint">
/// The URI endpoint to use for HTTP calls to the Dapr runtime. The default value will be 
/// <c>http://127.0.0.1:DAPR_HTTP_PORT</c> where <c>DAPR_HTTP_PORT</c> represents the value of the 
/// <c>DAPR_HTTP_PORT</c> environment variable.
/// </param>
/// <returns>The <see cref="DaprClientBuilder" /> instance.</returns>
public DaprClientBuilder UseHttpEndpoint(string httpEndpoint)
{
ArgumentVerifier.ThrowIfNullOrEmpty(httpEndpoint, nameof(httpEndpoint));
this.HttpEndpoint = httpEndpoint;
return this;
}

```
I hope the Java SDK also has this method.

（java sdk 里没有找到指定服务器地址的方法，在本地调试不能调用另一台电脑的部署的服务。）

**Comment by artursouza** [comment]
The Java SDK abstracts the gRPC and HTTP protocol (except the service invocation). So, if you need to connect to a different sidecar endpoint, use the Java properties in this file: https://github.com/dapr/java-sdk/blob/05bf66e0d4964b6588e8c5865c7902c53c89d636/sdk/src/main/java/io/dapr/config/Properties.java#L56

This is the "Java way" to provide configuration. The Java SDK is not necessarily a 1-1 mapping with the .Net SDK.
