### ISSUE TITLE
Enable gRPC port for ClientBuilder

### ISSUE THREAD

**Issue by yaron2** [dapr/java-sdk#65]
The ClientBuilder [always looks](https://github.com/dapr/java-sdk/blob/c571ac6ba6f7ba3416fa3a96883e1ae93a241ab9/sdk/src/main/java/io/dapr/client/AbstractClientBuilder.java#L45) for the Dapr HTTP env port, regardless if the the Client itself is HTTP or gRPC based.

**Comment by artursouza** [comment]
Thanks!

**Comment by artursouza** [comment]
Change to use the right port is in. Change to use GRPC instead of HTTP is separate.
