### ISSUE TITLE
add support for statestore query API

### ISSUE THREAD

**Issue by dmitsh** [dapr/java-sdk#653]
## Describe the proposal
This feature is implemented in dapr runtime: https://github.com/dapr/dapr/issues/3662

It should be available in the SDK

Also, add integration test validating this feature in SDK.

**Comment by artursouza** [comment]
Because this API is in alpha, it should probably be in a separate (new) client interface.

**Comment by dmitsh** [comment]
Thank you @mukundansundar for taking over this issue.
If that could help, I put together a corresponding PR for go-sdk: https://github.com/dapr/go-sdk/pull/216

**Comment by artursouza** [comment]
https://azure.github.io/azure-sdk/java_introduction.html#java-models-builder
