### ISSUE TITLE
Reach parity with Dapr features

### ISSUE THREAD

**Issue by yaron2** [dapr/java-sdk#66]
## Describe the proposal

Missing functionality that needs to be addressed:

1. Subscribe to topics
2. Bindings callbacks
3. Service invocation callback

I assume this is likely to be implemented in DaprClient

**Comment by yaron2** [comment]
These are currently manually implemented by the user by either exposing a web server with the required endpoints, or implementing the `daprclient` gRPC interface.

**Comment by artursouza** [comment]
Thanks, Yaron. I am aware of these gaps. Thanks for creating the issue.

**Comment by LMWF** [comment]
The part of this issue related to bindings: https://github.com/dapr/java-sdk/pull/81/
