### ISSUE TITLE
How do I configure ObjectMapper?

### ISSUE THREAD

**Issue by caobingsheng** [dapr/java-sdk#716]

**Comment by tanvigour** [comment]
What are you trying to achieve? Here's an example using object mapper https://docs.dapr.io/developing-applications/sdks/java/

**Comment by caobingsheng** [comment]
I need to use a custom date format, but ObjectMapper(Jackson) that DAPR uses cannot be configured.

**Comment by artursouza** [comment]
You can use Jackson annotation into our domain objects or bring your own serializer as pass it in the builder for DaprClient.

**Comment by caobingsheng** [comment]
Thanks!
