### ISSUE TITLE
kafka pubsub issue

### ISSUE THREAD

**Issue by Venkat1188** [dapr/java-sdk#739]
## Expected Behavior
Spring boot java application not able to send messages to kafka topic by using dapr client and dapr enable application

msg: rpc error: code = FailedPrecondition desc = no pubsub is configured, scope: dapr.runtime.grpc.api, type: log, ver: 1.6.0}
## Actual Behavior
Spring boot java application should able to send messages to Kafka topic by using dapr client and dapr enable application

Fallowed the java-sdk pubsub example

## Release Note

RELEASE NOTE:

**Comment by mukundansundar** [comment]
@Venkat1188 Have you configured the pubsub as expected by the application?

**Comment by mukundansundar** [comment]
@Venkat1188 Have you configured the pubsub as expected by the application?

**Comment by Venkat1188** [comment]
Yes,
Able to send messages to topic and I can see application subscribed to topic on dapr logs

**Comment by Venkat1188** [comment]
The main issue is while subscribing to a message from a topic getting an Nullpointer exception on 
cloudEvent.getData()

**Comment by mukundansundar** [comment]
> The main issue is while subscribing to a message from a topic getting an Nullpointer exception on
> cloudEvent.getData()

#743 discusses that. closing this issue
