### ISSUE TITLE
Change configuration API response to dictionary

### ISSUE THREAD

**Issue by amulyavarote** [dapr/java-sdk#746]
## Describe the proposal
Change the configuration API response to handle dictionary.
Main issue in dapr/dapr in pasted here.
https://github.com/dapr/dapr/issues/4556

**Comment by mukundansundar** [comment]
Since the parent issue(https://github.com/dapr/dapr/issues/4556) is targeted for 1.9 targeting this issue for 1.7 Java SDK

**Comment by pravinpushkar** [comment]
Dependent on PRs - 
https://github.com/dapr/components-contrib/pull/1771
https://github.com/dapr/dapr/pull/4695
