### ISSUE TITLE
Version support policy for dapr's SDK's is needed.

### ISSUE THREAD

**Issue by darren-wang** [dapr/java-sdk#749]
Hi all, since the version of dapr java sdk and the version of dapr runtime are different, and as a corporate user we cann't upgrade frequently, so I think a version support policy for dapr sdk is NEEDED.

I think every version of dapr sdk should specify the versions of dapr runtime which it supports, and for users who have a fixed version of dapr runtime can accordingly decide which version of dapr's sdk to use.

For example, we are using dapr 1.5.1, for corporate user it's not that easy to upgrade often, but now, I don't know which version of java sdk can be used to work with dapr v.1.5.1, java-sdk-v1.3.0? or java-sdk-latest?

**Comment by darren-wang** [comment]
@[artursouza](https://github.com/artursouza) could you hava a look at this proposal?

**Comment by tanvigour** [comment]
So sdk versions are always backward compatible with runtime versions. Basically in your example case, dapr 1.5.1 should work with java-sdk-latest.

**Comment by artursouza** [comment]
The supported versions based on release are here: https://docs.dapr.io/operations/support/support-release-policy/. The SDK can work with newer or older versions of the runtime unless there is a documented deprecation that was later on removed (breaking change).
