### ISSUE TITLE
How to make subscription dynamic?

### ISSUE THREAD

**Issue by MregXN** [dapr/java-sdk#780]
As the example below we could realise subscription via annotations. But topic and pubsubName is static, which means we cannot decide which topic to subscribe at runtime. What is more，If there are multiple topics to subscribe there will be a lot of duplicate code. Is there any more elegant subscription implementation via HTTP？

``` java
@RestController
public class CheckoutServiceController {

    private static final Logger log = LoggerFactory.getLogger(CheckoutServiceController.class);
     //Subscribe to a topic

    @Topic(name = "orders", pubsubName = "order-pub-sub")
    @PostMapping(path = "/checkout")
    public Mono<Void> getCheckout(@RequestBody(required = false) CloudEvent<String> cloudEvent) {
        return Mono.fromRunnable(() -> {
            try {
                log.info("Subscriber received: " + cloudEvent.getData());
            } catch (Exception e) {
                throw new RuntimeException(e);
            }
        });
    }
}
```

**Comment by pravinpushkar** [comment]
@MregXN Have you already explored content based routing for your scenario - https://docs.dapr.io/developing-applications/building-blocks/pubsub/howto-route-messages/

**Comment by MregXN** [comment]
Thanks!
