### ISSUE TITLE
Dapr Subuscriber Support for Non-Spring Boot Application

### ISSUE THREAD

**Issue by Vishal07051999** [dapr/java-sdk#784]
Hi Dapr Team,
We have been trying to use Dapr Java SDK in a KTOR based application.

Most of the cases work out of the box, only caveat that we have observed which is why we can't move full blown Dapr is lack of support in subscribers outside Spring boot world.

**Comment by skyao** [comment]
hi, @Vishal07051999, thank you for issue.

Do you want to support something like @topic annotation outside spring boot?

**Comment by artursouza** [comment]
You can still use Subscribe if you implement the request handler directly on the app.
