### ISSUE TITLE
Compatible with Spring Webflux + WebClient

### ISSUE THREAD

**Issue by rowi1de** [dapr/java-sdk#786]
## Ask your question here
I’ve seen Dapr includes spring-web and not webflux, even all methods build on project reactor types.

- Is it possible to add Dapr to a Spring WebFlux application? Spring boot would fall back to non-reactive stack if both starters are on the classpath 
-  Is it possible to use Spring WebClient instead of using Dapr client ? It has better kotlin support, fluent api and allows to be used with other spring components

**Comment by artursouza** [comment]
I appreciate examples of how these could work. Not an expert in WebFlux but I do think the SDK should work better with Kotlin overall.
