### ISSUE TITLE
Add ElementType.TYPE to ActorType

### ISSUE THREAD

**Issue by LionTao** [dapr/java-sdk#797]
## Describe the proposal

Hi, I want to use the actor model with Kotlin. Currently, the `ActorType` annotation in java is targeted at ElementType.TYPE_USE which is incompatible with kotlin interface.
Adding ElementType.TYPE to the annotation target field should work. Can we add it?

**Comment by artursouza** [comment]
Overall I am inclined. But what would be the difference?

**Comment by LionTao** [comment]
> Overall I am inclined. But what would be the difference?

**That would allow writing actor interfaces in kotlin.**
Currently I want to write my actor implemtation in kotlin but I have to write a java actor interface to use the java sdk features.

**Comment by mukundansundar** [comment]
@LionTao Will you be able to contribute a PR for this change?

**Comment by LionTao** [comment]
> @LionTao Will you be able to contribute a PR for this change?

Of course, created #812

**Comment by mukundansundar** [comment]
@LionTao Could you provide some documentation link in the PR or in this issue which explains why `ElementType.Type` is needed for Kotlin?

**Comment by LionTao** [comment]
> @LionTao Could you provide some documentation link in the PR or in this issue that explains why `ElementType.Type` is needed for Kotlin?

It seems currently kotlin lacks some native java ElementType enum value according to [Kotlin docs](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.annotation/-annotation-target/)

For my project, rewriting the ActorType annotation class with `ElementType.TYPE` will let it annotate a kotlin interface. Otherwise, the kotlin compiler throws an error that says `This annotation is not applicable to target 'interface'`.
