### ISSUE TITLE
❌  exec: " java": executable file not found in $PATH

### ISSUE THREAD

**Issue by ChristianWeyer** [dapr/java-sdk#799]
When I run this command for my sample app:

`dapr run --components-path ../components --app-id servicedaprized --app-port 3000 -- \ java -jar target/java-springboot-service-daprized-0.0.1-SNAPSHOT.jar com.tt.example.javaspringbootservicedaprized.JavaSpringbootServiceDaprizedApplication -p 3000`

I get the following error:
```
ℹ️  Starting Dapr with id servicedaprized. HTTP Port: 50106. gRPC Port: 50107
❌  exec: " java": executable file not found in $PATH
✅  Start App failed, try to stop Dapr successfully
```

`which java` on this terminal gives me:
`/usr/bin/java`

Any idea what I might be missing?
Thanks.

**Comment by mukundansundar** [comment]
@ChristianWeyer `" java"` seems that it is considering `\ java` as `" java"`. Can you try without the `\` ?

**Comment by ChristianWeyer** [comment]
Doh! Of course, you are right. Thanks, man.
