### ISSUE TITLE
Is there a way to subscribe to topic and get data

### ISSUE THREAD

**Issue by blublinsky** [dapr/java-sdk#8]
## Ask your question here
An example here shows how to publish event, but provides no information on how to subscribe and receive events?
I can see Node and Python examples at https://github.com/dapr/samples/tree/master/4.pub-sub,
But they are not easily transferable to java

**Comment by amanbha** [comment]
@blublinsky  The subscription in dapr is similar across all languages:
Dapr will call into the app over http or grpc.
1. The app should have a /subscribe route which will return a json list of Topics it wants to subscribe to (https://github.com/dapr/docs/blob/master/reference/api/pubsub.md#handling-topic-subscriptions)
2 Lets say, the app subscribes to 2 topics: Deposit & Withdraw, then the app also needs to have 2 routes  on /Deposit & /Withdraw to recieve the events for the subscribed topics, (https://github.com/dapr/docs/blob/master/reference/api/pubsub.md#delivering-events-to-subscribers)

**Comment by blublinsky** [comment]
Thanks @amanbha.
It is a bit confusing, because publish is a GRPC API, but subscribe is not. Why is it asymmetric?
I see some of the methods for subscribe are in GRPCClient, but they seem not been implemented .
Am I missing something?

**Comment by amanbha** [comment]
> Thanks @amanbha.
> It is a bit confusing, because publish is a GRPC API, but subscribe is not. Why is it asymmetric?
> I see some of the methods for subscribe are in GRPCClient, but they seem not been implemented .
> Am I missing something?

@blublinsky I understand the confusion, allow me to explain a bit more detail. User App and Dapr can interact with each other over gRPC or HTTP. The Java SDK is autogenerated from the proto files of gRPC apis in Dapr runtime. 
You can also make http calls directly to (publish the events to a topic)[https://github.com/dapr/docs/blob/master/reference/api/pubsub.md#publish-a-message-to-a-given-topic]

**Comment by blublinsky** [comment]
Thanks @amanbha.
Did some more experiments. I finally realized that DaprClient.proto defines an interface that I need to implement to respond to Dapr requests. The issue that I am getting into with this approach is that I need 2 GRPC channels one for invoking DAPR and one for responding to DAPR request. 
Is there a way to tell DAPR environment to use these 2 channels, defining which one to use for what?

**Comment by blublinsky** [comment]
After more experimentations, it looks like, the right configuration is:
 dapr run --app-id scalaTest --grpc-port 50001 --app-port 50002 --protocol grpc --port 3500 -- sbt run,
but it does not work - 
Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/0:0:0:0:0:0:0:1:50001
If I remove 
--app-port 50002 --protocol grpc
DAPR obviously does not know how to access my app.
So it looks like 2 GRCP channels are not supported

**Comment by amanbha** [comment]
@blublinsky  The command looks correct, when you provide the --protocol grpc flag, the app-port is treated as gRPC port.  There will be 2 channels, App-> Dapr(Dapr runtime listening on port 50001) & Dapr->app(App listening on port 50002). It should have worked.
cc @yaron2 & @youngbupark for further help.

**Comment by blublinsky** [comment]
I can provide a project if this will help

**Comment by amanbha** [comment]
> I can provide a project if this will help

Thanks @blublinsky , that would be very helpful.

**Comment by blublinsky** [comment]
[dapr.zip](https://github.com/dapr/java-sdk/files/3763533/dapr.zip)
Uploaded

**Comment by blublinsky** [comment]
Its Scala, not Java, but should be the same

**Comment by blublinsky** [comment]
With more experiments it looks like Dapr currently does not support bidirectional communications with an applications.
Additionally, once this is fixed, feel free to use this example as scala APIs

**Comment by yaron2** [comment]
Hey @blublinsky , in order for Dapr to talk to your app via gRPC, your app needs to implement the daprclient service.
For Java/Scala, that would be:

https://github.com/dapr/java-sdk/blob/master/src/main/java/io/dapr/DaprClientProtos.java

See this document on how to use gRPC and Dapr:
https://github.com/dapr/docs/tree/master/howto/create-grpc-app

**Comment by blublinsky** [comment]
Its implemented, take a look at the code provided and works by itself.
The issue is that bidirectional communications do not work. I can either talk to runtime or receive runtime messages, but not both in the same app

**Comment by yaron2** [comment]
In gRPC bidirectional communications implies a streaming nature, but that's just a design decision.

For example, Dapr will call your app on the `GetTopicSubscriptions ` method to get your topic subscriptions, and then when a message comes it will call you via `OnTopicEvent`.

Regardless, you could publish a message by invoking Dapr over gRPC with the `PublishEvent` method.

**Comment by blublinsky** [comment]
But it does not work. Please, take a look at enclosed code. I might be missing something,but I am creating two channels - one for listening on Dapr and one for accessing Dapr. each channel works by itself, but both in one app fail

**Comment by yaron2** [comment]
Yeah I'll take a look and report back.

**Comment by blublinsky** [comment]
@yaron2 any feedback on this?
Also, is there are example of using Actors?

**Comment by artursouza** [comment]
We activelly working on the Java-SDK now. We do have examples in this repo now:

https://github.com/dapr/java-sdk

For the WIP on the Java-SDK, follow https://github.com/dapr/java-sdk/tree/java_sdk_wip

**Comment by artursouza** [comment]
https://github.com/dapr/java-sdk/tree/master/examples/src/main/java/io/dapr/examples/pubsub/http
