### ISSUE TITLE
Incorrect type conversion for objects in a map

### ISSUE THREAD

**Issue by michapojo** [dapr/java-sdk#802]
## Expected Behavior

In my service, I'm using dapr for saving and quering a entity with various attributes. The used db is a MongoDB.
One attribute is of type LinkedHashMap<String, Object>, because its content is very dynamic.

The content of this linkedHashMap attribute should be consistent, when query it.

## Actual Behavior

The saving of this entity works fine.
The problem occurs, when trying to retrieve a integer value.
In the DB it is saved correctly. I.e. 
```
"linkedHashMapAttribute": {
      "intValue": 2
}
```
Returned LinkedHashMap is filled with 
intValue: 2.0

The returned value by dapr seems not to be correct even before deserialization
https://github.com/dapr/java-sdk/blob/master/sdk/src/main/java/io/dapr/client/ObjectSerializer.java#L141

## Steps to Reproduce the Problem

- Save an entity with a LinkedHashMap attribute (filled with an integer value) into a db.
- Verify the content in the DB
- Query the entity
- Check the returned value for the linkedHashMap attribute

## Release Note

RELEASE NOTE:

**Comment by michapojo** [comment]
Further informations:
It seems that the root cause of the problem is the save state operation.
https://github.com/dapr/java-sdk/blob/master/sdk/src/main/java/io/dapr/client/DaprClient.java#L480

When i insert a integer value manually into the db, the value is returned correctly

**Comment by MregXN** [comment]
Hi，I simply used the [official example of dapr state_management](https://github.com/dapr/quickstarts/tree/master/state_management/java/sdk) and replaced redis with mongoDB. **But I didn`t reproduced this problem.**

This example also uses the save state operation to store an int value.  My component yaml is as follow:

```yaml
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: statestore
spec:
  type: state.mongodb
  version: v1
  metadata:
  - name: host
    value: localhost:27017
```

Hope it can be helpful to you.

**Comment by michapojo** [comment]
Thanks for helping @MregXN but this didn't solve my issue.
Anyway I changed the implemetation on our side.

This is a very specific case so I think the issue can be closed.
