### ISSUE TITLE
Missing csrf error --> 403 with subscriber

### ISSUE THREAD

**Issue by Piet2001** [dapr/java-sdk#804]
## Ask your question here

When i have a post request in spring boot for the subscriber. It gives a 403 for missing csrf token from spring security.
Anyone with experiance how to work with this?

**Comment by artursouza** [comment]
Does the spring application require an authentication token?

**Comment by Piet2001** [comment]
Yeah, we have implemented a azure connection to verify user roles

**Comment by Piet2001** [comment]
We disabled CSRF to fix it
