### ISSUE TITLE
Workflow implementation in SDK

### ISSUE THREAD

**Issue by RyanLettieri** [dapr/java-sdk#839]
## Describe the proposal
Add Java SDK support for dapr workflow. This will include both the authoring and management functionalities.

Related dapr/dapr proposal: https://github.com/dapr/dapr/issues/4576

**Comment by artursouza** [comment]
I think the management APIs are P1 but authoring is a P2. Maybe we should have separate issues, one for each?

**Comment by RyanLettieri** [comment]
@dapr/maintainers-java-sdk can we move this from the v1.10 milestone to the v1.12 milestone?

**Comment by mukundansundar** [comment]
> @dapr/maintainers-java-sdk can we move this from the v1.10 milestone to the v1.12 milestone?

This milestone is Java sdk milestone. Which is 1.10. Current version is 1.8. 1.9 is current milestone and 1.10 is the next one.

**Comment by bderusha** [comment]
My team is interested in contributing some of this implementation. Is there anyone else currently working on this that we should coordinate with?

**Comment by bderusha** [comment]
@dapr/maintainers-java-sdk Would love to get early feedback on this WIP PR #857 to validate the overall approach
