### ISSUE TITLE
Migrate to JUnit 5

### ISSUE THREAD

**Issue by artursouza** [dapr/java-sdk#875]
## Describe the proposal

~All~ Some tests are using JUnit 4 - migrate all of them to JUnit 5.

**Comment by ejba** [comment]
Can I take this task?

**Comment by cicoyle** [comment]
Is anyone actively working on this? @Nancy64-bit

**Comment by ejba** [comment]
@cicoyle I had to pause my work for a while due to personal problems. Meanwhile @Nancy64-bit assigned to the task, so I will wait for @Nancy64-bit's feedback.

**Comment by ejba** [comment]
@cicoyle I believe this work fixes #904
