### ISSUE TITLE
[Proposal] Migrate `waitForSidecar` to `v1.0/healthz/outbound` to provide parity with dotnet SDK

### ISSUE THREAD

**Issue by olitomlinson** [dapr/java-sdk#897]
## Describe the proposal

- In `WaitForSidecarAsync` in the dotnet SDK, it waits for a specific health check against `v1.0/healthz/outbound` https://github.com/dapr/dotnet-sdk/blob/17f849b17505b9a61be1e7bd3e69586718b9fdd3/src/Dapr.Client/DaprClientGrpc.cs#L1758-L1785

- In `waitForSidecar` in the Java SDK, it just waits for the dapr http port to become available https://github.com/dapr/java-sdk/blob/cf8040dd6d2e77b7e81d646e2496b871ade92fe4/sdk/src/main/java/io/dapr/client/DaprClientHttp.java#L138-L146

In my opinion, the dotnet SDK provides a more explicit implementation that is better isolated from accidental change. 

For example, if the ordering of a dapr runtime init ever changed (accidentally or deliberately), and the dapr http port was open **before** all components were initialised, then this would cause a break in behaviour.

Therefore, for this reason, I propose that the Java SDK (and other SDKs) should follow the same behaviour as the dotnet SDK and wait for a successful response from `v1.0/healthz/outbound` rather than just waiting for the dapr http port to be open.

---

This is my understanding of the relationship between Dapr and the App during init

![image](https://github.com/dapr/java-sdk/assets/4224880/9ba5af7b-b085-4ab7-86b9-6ef73a472ec4)

**Comment by cicoyle** [comment]
[once the docs PR I have open gets merged](https://github.com/dapr/java-sdk/pull/981), then this issue can be closed.
