### ISSUE TITLE
Document the process for uploading Maven package to repository/

### ISSUE THREAD

**Issue by amanbha** [dapr/java-sdk#9]
This can be added to the wiki for the repo.

**Comment by youngbupark** [comment]
@shalabhms I think it would be good to have actions ci as well.

**Comment by artursouza** [comment]
@youngbupark  This issue sees to be related to the CD work.

**Comment by yaron2** [comment]
@shalabhms can help out here

**Comment by artursouza** [comment]
Resolving this since @youngbupark did document it in a wiki after his contribution to our CI/CD pipeline.

https://github.com/dapr/java-sdk/wiki/Release-Process
