### ISSUE TITLE
Cannot schedule a workflow at a specific date/time

### ISSUE THREAD

**Issue by rabollin** [dapr/java-sdk#943]
In the existing implementation I cannot see the ability to pass date/ time to schedule the workflow/ activity run as per the below code at : https://github.com/dapr/java-sdk/blob/master/sdk-workflows/src/main/java/io/dapr/workflows/client/DaprWorkflowClient.java

 public <T extends Workflow> String scheduleNewWorkflow(Class<T> clazz) {
    return this.innerClient.scheduleNewOrchestrationInstance(clazz.getCanonicalName());
  }

  /**
   * Schedules a new workflow using DurableTask client.
   *
   * @param <T>   any Workflow type
   * @param clazz Class extending Workflow to start an instance of.
   * @param input the input to pass to the scheduled orchestration instance. Must be serializable.
   * @return the randomly-generated instance ID for new Workflow instance.
   */
  public <T extends Workflow> String scheduleNewWorkflow(Class<T> clazz, Object input) {
    return this.innerClient.scheduleNewOrchestrationInstance(clazz.getCanonicalName(), input);
  }

  /**
   * Schedules a new workflow using DurableTask client.
   *
   * @param <T>        any Workflow type
   * @param clazz      Class extending Workflow to start an instance of.
   * @param input      the input to pass to the scheduled orchestration instance. Must be serializable.
   * @param instanceId the unique ID of the orchestration instance to schedule
   * @return the <code>instanceId</code> parameter value.
   */
  public <T extends Workflow> String scheduleNewWorkflow(Class<T> clazz, Object input, String instanceId) {
    return this.innerClient.scheduleNewOrchestrationInstance(clazz.getCanonicalName(), input, instanceId);
  }

However I can schedule it either with Python/ dotnet;  Refer to dotnet SDK here: https://github.com/dapr/dotnet-sdk/blob/master/src/Dapr.Workflow/DaprWorkflowClient.cs

@skyao - FYA.

**Comment by kaibocai** [comment]
Seems we need another wrapper method for this https://github.com/microsoft/durabletask-java/blob/8a74001f64aa4048c1619c14b7657c8b3b8993af/client/src/main/java/com/microsoft/durabletask/DurableTaskClient.java#L78
