### ISSUE TITLE
有关于分布式事务的组件吗，或者可以通过pubsub或者状态存储实现分布式事务（Are there any components related to distributed transactions, or can distributed transactions be implemented through pubsub or state storage）

### ISSUE THREAD

**Issue by suyuzhan001** [dapr/java-sdk#948]

**Comment by suyuzhan001** [comment]
Are there any components related to distributed transactions, or can distributed transactions be implemented through pubsub or state storage

**Comment by skyao** [comment]
@suyuzhan001 thank you for your question, it's really a good question! 

The answer is Yes! Dapr is planning to provide distributed transaction support by Saga pattern which will based on Dapr Workflow.

The first alpha version of Saga pattern support will be included in the next Dapr release v1.13 and first available  in Java SDK.

The design is still in internal discussion, and we will open a proposal to community soon. 

if you have interesting in this proposal, you can go this PR and try the quickstart of saga pattern support in Java SDK: 

https://github.com/dapr/quickstarts/pull/954
