### ISSUE TITLE
fossa test is keep failing

### ISSUE THREAD

**Issue by MregXN** [dapr/java-sdk#974]
## Expected Behavior

pass or fail based on the actual situation

## Actual Behavior

It always fails and there are logs outputting as follow：
```
Error:  A push-only API key was used, so issue details cannot be displayed.
  Check the webapp for issue details, or rerun this command with a full-access API key.
```

For more details: https://github.com/dapr/java-sdk/actions/workflows/fossa.yml

**Comment by artursouza** [comment]
This is working again. Also, the FOSSA error is an exception due to the package being dual-license.
